//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark -

//
// File: Payload/HQ-iOS.app/Frameworks/DropKit.framework/DropKit
// UUID: 93F55FEA-ED2B-3CBB-A0AA-9E62FAA00BAC
//
//                           Arch: arm64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 0.0.0.0.0
//
// Objective-C Garbage Collection: Unsupported
//
//                       Run path: /usr/lib/swift
//                               = /usr/lib/swift
//                       Run path: @executable_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/DropKit.framework/Frameworks
//                       Run path: @loader_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/DropKit.framework/Frameworks
//                       Run path: @executable_path/../../Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/DropKit.framework/../../Frameworks
//                       Run path: @executable_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/DropKit.framework/Frameworks
//                       Run path: @loader_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/DropKit.framework/Frameworks
//

@interface _TtC7DropKit33ProductOfferSessionViewController : UIViewController
{
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: socketCommand
    // Error parsing type: , name: socketCommands
    // Error parsing type: , name: socketMessages
    // Error parsing type: , name: productOfferPurchaseStarted
    // Error parsing type: , name: productOfferApplePayDidComplete
    // Error parsing type: , name: $__lazy_storage_$_productOffersRemainingView
    // Error parsing type: , name: $__lazy_storage_$_productOffersRemainingLabel
    // Error parsing type: , name: $__lazy_storage_$_productOfferNameLabel
    // Error parsing type: , name: $__lazy_storage_$_productOfferDescriptionLabel
    // Error parsing type: , name: $__lazy_storage_$_productOfferExpiresInLabel
    // Error parsing type: , name: $__lazy_storage_$_productOfferView
    // Error parsing type: , name: $__lazy_storage_$_productOfferDetailsView
    // Error parsing type: , name: $__lazy_storage_$_productOfferImageView
    // Error parsing type: , name: $__lazy_storage_$_activityIndicator
    // Error parsing type: , name: $__lazy_storage_$_productOfferButtonContainerView
    // Error parsing type: , name: $__lazy_storage_$_productOfferPurchaseButton
    // Error parsing type: , name: bottomAnchor
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end

@interface _TtC7DropKit11BundleClass : _TtCs12_SwiftObject
{
}

@end

@interface _TtC7DropKit40ProductOfferPurchaseResultViewController : UIViewController
{
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: productOfferPurchaseResult
    // Error parsing type: , name: $__lazy_storage_$_productOfferResultView
    // Error parsing type: , name: $__lazy_storage_$_productOfferResultDetailView
    // Error parsing type: , name: $__lazy_storage_$_productOfferResultTitleLabel
    // Error parsing type: , name: $__lazy_storage_$_productOfferDetailTitle
    // Error parsing type: , name: $__lazy_storage_$_productOfferImageView
    // Error parsing type: , name: $__lazy_storage_$_productOfferDetailSubtitle
    // Error parsing type: , name: $__lazy_storage_$_productOfferDismissButton
    // Error parsing type: , name: $__lazy_storage_$_productOfferDismissXButton
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end

@interface _TtC7DropKit11DropService : _TtCs12_SwiftObject
{
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: gameWatchdog
    // Error parsing type: , name: sessions
}

@end

@interface _TtC7DropKit11DropSession : _TtCs12_SwiftObject
{
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: gameWatchdog
    // Error parsing type: , name: productOfferCommand
    // Error parsing type: , name: socketCommands
    // Error parsing type: , name: socketMessages
    // Error parsing type: , name: shopifyClient
    // Error parsing type: , name: productOfferApplePayDidComplete
    // Error parsing type: , name: productOfferPurchaseComplete
    // Error parsing type: , name: productOfferShopifyDidComplete
    // Error parsing type: , name: productOfferPurchaseStarted
    // Error parsing type: , name: isProductOfferEnded
    // Error parsing type: , name: isProductPurchaseInProgress
    // Error parsing type: , name: isShopifyCheckoutCompleted
    // Error parsing type: , name: productOfferPurchaseEnded
    // Error parsing type: , name: productOfferSessionEnded
    // Error parsing type: , name: $__lazy_storage_$_productOfferSessionViewController
    // Error parsing type: , name: checkoutInput
    // Error parsing type: , name: currentCheckout
    // Error parsing type: , name: paySession
    // Error parsing type: , name: productPurchaseStartedMessage
    // Error parsing type: , name: lastOrderId
    // Error parsing type: , name: lastCustomerId
    // Error parsing type: , name: lastAddress
}

@end

