//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark Named Structures

struct CGPoint {
    double _field1;
    double _field2;
};

struct CGRect {
    struct CGPoint _field1;
    struct CGSize _field2;
};

struct CGSize {
    double _field1;
    double _field2;
};

#pragma mark -

//
// File: Payload/HQ-iOS.app/Frameworks/Words.framework/Words
// UUID: D7E7AE8C-2954-3AB2-841D-11A9414E1D67
//
//                           Arch: arm64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 0.0.0.0.0
//
// Objective-C Garbage Collection: Unsupported
//
//                       Run path: /usr/lib/swift
//                               = /usr/lib/swift
//                       Run path: @executable_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/Words.framework/Frameworks
//                       Run path: @loader_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/Words.framework/Frameworks
//                       Run path: @executable_path/../../Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/Words.framework/../../Frameworks
//                       Run path: @executable_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/Words.framework/Frameworks
//                       Run path: @loader_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/Words.framework/Frameworks
//

@protocol AVAudioPlayerDelegate <NSObject>

@optional
- (void)audioPlayerEndInterruption:(AVAudioPlayer *)arg1;
- (void)audioPlayerEndInterruption:(AVAudioPlayer *)arg1 withFlags:(unsigned long long)arg2;
- (void)audioPlayerEndInterruption:(AVAudioPlayer *)arg1 withOptions:(unsigned long long)arg2;
- (void)audioPlayerBeginInterruption:(AVAudioPlayer *)arg1;
- (void)audioPlayerDecodeErrorDidOccur:(AVAudioPlayer *)arg1 error:(NSError *)arg2;
- (void)audioPlayerDidFinishPlaying:(AVAudioPlayer *)arg1 successfully:(_Bool)arg2;
@end

@protocol CAAnimationDelegate <NSObject>

@optional
- (void)animationDidStop:(CAAnimation *)arg1 finished:(_Bool)arg2;
- (void)animationDidStart:(CAAnimation *)arg1;
@end

@protocol NSObject
@property(nonatomic, readonly) NSString *description;
- (struct _NSZone *)zone;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (_Bool)respondsToSelector:(SEL)arg1;
- (_Bool)conformsToProtocol:(Protocol *)arg1;
- (_Bool)isMemberOfClass:(Class)arg1;
- (_Bool)isKindOfClass:(Class)arg1;
- (_Bool)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (id)self;
- (Class)class;
@property(nonatomic, readonly) Class superclass;
@property(nonatomic, readonly) long long hash;
- (_Bool)isEqual:(id)arg1;

@optional
@property(nonatomic, readonly) NSString *debugDescription;
@end

@protocol SLCoreAnimationBuildDelegate <NSObject>

@optional
- (void)squallCoreAnimation:(SLCoreAnimation *)arg1 willBuildAnimationsForLayer:(CALayer<SLLayerProtocol> *)arg2 withName:(NSString *)arg3;
- (void)squallCoreAnimationDidLayoutAnimationLayers:(SLCoreAnimation *)arg1;
- (CAAnimationGroup *)shouldAddAnimations:(CAAnimationGroup *)arg1 toLayer:(CALayer *)arg2 withName:(NSString *)arg3;
@end

@protocol SLLayerProtocol <NSObject>
- (SLProperty *)propertyWithPath:(NSString *)arg1;
- (SLProperty *)propertyWithName:(NSString *)arg1;
- (NSArray *)markersWithComment:(NSString *)arg1;
- (void)evaluateExpressions;
@property(nonatomic, readonly) NSArray *markers;
@property(nonatomic, readonly) NSArray *properties;
@property(nonatomic, readonly) NSArray *expressionControls;
@end

@protocol UIActivityItemSource <NSObject>
- (id)activityViewController:(UIActivityViewController *)arg1 itemForActivityType:(NSString *)arg2;
- (id)activityViewControllerPlaceholderItem:(UIActivityViewController *)arg1;

@optional
- (UIImage *)activityViewController:(UIActivityViewController *)arg1 thumbnailImageForActivityType:(NSString *)arg2 suggestedSize:(struct CGSize)arg3;
- (NSString *)activityViewController:(UIActivityViewController *)arg1 dataTypeIdentifierForActivityType:(NSString *)arg2;
- (NSString *)activityViewController:(UIActivityViewController *)arg1 subjectForActivityType:(NSString *)arg2;
@end

@protocol UIScrollViewDelegate <NSObject>

@optional
- (void)scrollViewDidChangeAdjustedContentInset:(UIScrollView *)arg1;
- (void)scrollViewDidScrollToTop:(UIScrollView *)arg1;
- (_Bool)scrollViewShouldScrollToTop:(UIScrollView *)arg1;
- (void)scrollViewDidEndZooming:(UIScrollView *)arg1 withView:(UIView *)arg2 atScale:(double)arg3;
- (void)scrollViewWillBeginZooming:(UIScrollView *)arg1 withView:(UIView *)arg2;
- (UIView *)viewForZoomingInScrollView:(UIScrollView *)arg1;
- (void)scrollViewDidEndScrollingAnimation:(UIScrollView *)arg1;
- (void)scrollViewDidEndDecelerating:(UIScrollView *)arg1;
- (void)scrollViewWillBeginDecelerating:(UIScrollView *)arg1;
- (void)scrollViewDidEndDragging:(UIScrollView *)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillEndDragging:(UIScrollView *)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewWillBeginDragging:(UIScrollView *)arg1;
- (void)scrollViewDidZoom:(UIScrollView *)arg1;
- (void)scrollViewDidScroll:(UIScrollView *)arg1;
@end

@protocol UITableViewDataSource <NSObject>
- (UITableViewCell *)tableView:(UITableView *)arg1 cellForRowAtIndexPath:(NSIndexPath *)arg2;
- (long long)tableView:(UITableView *)arg1 numberOfRowsInSection:(long long)arg2;

@optional
- (void)tableView:(UITableView *)arg1 moveRowAtIndexPath:(NSIndexPath *)arg2 toIndexPath:(NSIndexPath *)arg3;
- (void)tableView:(UITableView *)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(NSIndexPath *)arg3;
- (long long)tableView:(UITableView *)arg1 sectionForSectionIndexTitle:(NSString *)arg2 atIndex:(long long)arg3;
- (NSArray *)sectionIndexTitlesForTableView:(UITableView *)arg1;
- (_Bool)tableView:(UITableView *)arg1 canMoveRowAtIndexPath:(NSIndexPath *)arg2;
- (_Bool)tableView:(UITableView *)arg1 canEditRowAtIndexPath:(NSIndexPath *)arg2;
- (NSString *)tableView:(UITableView *)arg1 titleForFooterInSection:(long long)arg2;
- (NSString *)tableView:(UITableView *)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(UITableView *)arg1;
@end

@protocol UITableViewDelegate <NSObject, UIScrollViewDelegate>

@optional
- (void)tableView:(UITableView *)arg1 willEndContextMenuInteractionWithConfiguration:(UIContextMenuConfiguration *)arg2 animator:(id <UIContextMenuInteractionAnimating>)arg3;
- (void)tableView:(UITableView *)arg1 willDisplayContextMenuWithConfiguration:(UIContextMenuConfiguration *)arg2 animator:(id <UIContextMenuInteractionAnimating>)arg3;
- (void)tableView:(UITableView *)arg1 willPerformPreviewActionForMenuWithConfiguration:(UIContextMenuConfiguration *)arg2 animator:(id <UIContextMenuInteractionCommitAnimating>)arg3;
- (UITargetedPreview *)tableView:(UITableView *)arg1 previewForDismissingContextMenuWithConfiguration:(UIContextMenuConfiguration *)arg2;
- (UITargetedPreview *)tableView:(UITableView *)arg1 previewForHighlightingContextMenuWithConfiguration:(UIContextMenuConfiguration *)arg2;
- (UIContextMenuConfiguration *)tableView:(UITableView *)arg1 contextMenuConfigurationForRowAtIndexPath:(NSIndexPath *)arg2 point:(struct CGPoint)arg3;
- (void)tableViewDidEndMultipleSelectionInteraction:(UITableView *)arg1;
- (void)tableView:(UITableView *)arg1 didBeginMultipleSelectionInteractionAtIndexPath:(NSIndexPath *)arg2;
- (_Bool)tableView:(UITableView *)arg1 shouldBeginMultipleSelectionInteractionAtIndexPath:(NSIndexPath *)arg2;
- (_Bool)tableView:(UITableView *)arg1 shouldSpringLoadRowAtIndexPath:(NSIndexPath *)arg2 withContext:(id <UISpringLoadedInteractionContext>)arg3;
- (_Bool)tableView:(UITableView *)arg1 selectionFollowsFocusForRowAtIndexPath:(NSIndexPath *)arg2;
- (NSIndexPath *)indexPathForPreferredFocusedViewInTableView:(UITableView *)arg1;
- (void)tableView:(UITableView *)arg1 didUpdateFocusInContext:(UITableViewFocusUpdateContext *)arg2 withAnimationCoordinator:(UIFocusAnimationCoordinator *)arg3;
- (_Bool)tableView:(UITableView *)arg1 shouldUpdateFocusInContext:(UITableViewFocusUpdateContext *)arg2;
- (_Bool)tableView:(UITableView *)arg1 canFocusRowAtIndexPath:(NSIndexPath *)arg2;
- (void)tableView:(UITableView *)arg1 performAction:(SEL)arg2 forRowAtIndexPath:(NSIndexPath *)arg3 withSender:(id)arg4;
- (_Bool)tableView:(UITableView *)arg1 canPerformAction:(SEL)arg2 forRowAtIndexPath:(NSIndexPath *)arg3 withSender:(id)arg4;
- (_Bool)tableView:(UITableView *)arg1 shouldShowMenuForRowAtIndexPath:(NSIndexPath *)arg2;
- (long long)tableView:(UITableView *)arg1 indentationLevelForRowAtIndexPath:(NSIndexPath *)arg2;
- (NSIndexPath *)tableView:(UITableView *)arg1 targetIndexPathForMoveFromRowAtIndexPath:(NSIndexPath *)arg2 toProposedIndexPath:(NSIndexPath *)arg3;
- (void)tableView:(UITableView *)arg1 didEndEditingRowAtIndexPath:(NSIndexPath *)arg2;
- (void)tableView:(UITableView *)arg1 willBeginEditingRowAtIndexPath:(NSIndexPath *)arg2;
- (_Bool)tableView:(UITableView *)arg1 shouldIndentWhileEditingRowAtIndexPath:(NSIndexPath *)arg2;
- (UISwipeActionsConfiguration *)tableView:(UITableView *)arg1 trailingSwipeActionsConfigurationForRowAtIndexPath:(NSIndexPath *)arg2;
- (UISwipeActionsConfiguration *)tableView:(UITableView *)arg1 leadingSwipeActionsConfigurationForRowAtIndexPath:(NSIndexPath *)arg2;
- (NSArray *)tableView:(UITableView *)arg1 editActionsForRowAtIndexPath:(NSIndexPath *)arg2;
- (NSString *)tableView:(UITableView *)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(NSIndexPath *)arg2;
- (long long)tableView:(UITableView *)arg1 editingStyleForRowAtIndexPath:(NSIndexPath *)arg2;
- (void)tableView:(UITableView *)arg1 didDeselectRowAtIndexPath:(NSIndexPath *)arg2;
- (void)tableView:(UITableView *)arg1 didSelectRowAtIndexPath:(NSIndexPath *)arg2;
- (NSIndexPath *)tableView:(UITableView *)arg1 willDeselectRowAtIndexPath:(NSIndexPath *)arg2;
- (NSIndexPath *)tableView:(UITableView *)arg1 willSelectRowAtIndexPath:(NSIndexPath *)arg2;
- (void)tableView:(UITableView *)arg1 didUnhighlightRowAtIndexPath:(NSIndexPath *)arg2;
- (void)tableView:(UITableView *)arg1 didHighlightRowAtIndexPath:(NSIndexPath *)arg2;
- (_Bool)tableView:(UITableView *)arg1 shouldHighlightRowAtIndexPath:(NSIndexPath *)arg2;
- (void)tableView:(UITableView *)arg1 accessoryButtonTappedForRowWithIndexPath:(NSIndexPath *)arg2;
- (long long)tableView:(UITableView *)arg1 accessoryTypeForRowWithIndexPath:(NSIndexPath *)arg2;
- (UIView *)tableView:(UITableView *)arg1 viewForFooterInSection:(long long)arg2;
- (UIView *)tableView:(UITableView *)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(UITableView *)arg1 estimatedHeightForFooterInSection:(long long)arg2;
- (double)tableView:(UITableView *)arg1 estimatedHeightForHeaderInSection:(long long)arg2;
- (double)tableView:(UITableView *)arg1 estimatedHeightForRowAtIndexPath:(NSIndexPath *)arg2;
- (double)tableView:(UITableView *)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(UITableView *)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(UITableView *)arg1 heightForRowAtIndexPath:(NSIndexPath *)arg2;
- (void)tableView:(UITableView *)arg1 didEndDisplayingFooterView:(UIView *)arg2 forSection:(long long)arg3;
- (void)tableView:(UITableView *)arg1 didEndDisplayingHeaderView:(UIView *)arg2 forSection:(long long)arg3;
- (void)tableView:(UITableView *)arg1 didEndDisplayingCell:(UITableViewCell *)arg2 forRowAtIndexPath:(NSIndexPath *)arg3;
- (void)tableView:(UITableView *)arg1 willDisplayFooterView:(UIView *)arg2 forSection:(long long)arg3;
- (void)tableView:(UITableView *)arg1 willDisplayHeaderView:(UIView *)arg2 forSection:(long long)arg3;
- (void)tableView:(UITableView *)arg1 willDisplayCell:(UITableViewCell *)arg2 forRowAtIndexPath:(NSIndexPath *)arg3;
@end

@interface _TtC5Words7KeyTile : UIControl
{
    // Error parsing type: , name: kBackgroundColorAnimation
    // Error parsing type: , name: kScaleAnimation
    // Error parsing type: , name: kOpacityAnimation
    // Error parsing type: , name: kFlipAnimation
    // Error parsing type: , name: clearTimer
    // Error parsing type: , name: isRevealed
    // Error parsing type: , name: onDidTouchDown
    // Error parsing type: , name: onPressed
    // Error parsing type: , name: locked
    // Error parsing type: , name: delegate
    // Error parsing type: , name: $__lazy_storage_$_container
    // Error parsing type: , name: $__lazy_storage_$_label
    // Error parsing type: , name: style
    // Error parsing type: , name: character
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)onTouch;
- (void)onTouchDown;
- (id)initWithCoder:(id)arg1;
- (id)init;
@property(nonatomic) _Bool highlighted;
- (_Bool)isHighlighted;
@property(nonatomic) _Bool selected;
- (_Bool)isSelected;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words20WordsWinnersListView : UIView <UITableViewDelegate, UITableViewDataSource>
{
    // Error parsing type: , name: currentItems
    // Error parsing type: , name: $__lazy_storage_$_threeWinnerView
    // Error parsing type: , name: $__lazy_storage_$_youWinnerView
    // Error parsing type: , name: onShare
    // Error parsing type: , name: $__lazy_storage_$_gradientView
    // Error parsing type: , name: $__lazy_storage_$_blueCircleAnimation
    // Error parsing type: , name: $__lazy_storage_$_blueCircleMaskAnimation
    // Error parsing type: , name: $__lazy_storage_$_yellowCircleAnimation
    // Error parsing type: , name: $__lazy_storage_$_yellowCircleMaskAnimation
    // Error parsing type: , name: $__lazy_storage_$_circleAnimation
    // Error parsing type: , name: $__lazy_storage_$_tableViewContainer
    // Error parsing type: , name: fullscreenContainer
    // Error parsing type: , name: $__lazy_storage_$_tableView
    // Error parsing type: , name: useMasks
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)layoutSubviews;
- (void)traitCollectionDidChange:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words16WordsRadialBurst : CALayer
{
    // Error parsing type: , name: $__lazy_storage_$_replicator
    // Error parsing type: , name: diameter
    // Error parsing type: , name: thickness
    // Error parsing type: , name: rotation
    // Error parsing type: , name: $__lazy_storage_$_particle
    // Error parsing type: , name: color
    // Error parsing type: , name: rays
}

- (void).cxx_destruct;
- (id)initWithLayer:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words17WordsWinnersScene : _TtC5Words5Scene
{
    // Error parsing type: , name: presenter
    // Error parsing type: , name: controller
    // Error parsing type: , name: currentEvent
    // Error parsing type: , name: winnerView
}

- (void).cxx_destruct;

@end

@interface _TtC5Words20WordsGameCoordinator : NSObject <NSObject>
{
    // Error parsing type: , name: childCoordinators
    // Error parsing type: , name: delegate
    // Error parsing type: , name: layoutConfiguration
    // Error parsing type: , name: presentingViewController
    // Error parsing type: , name: appDependency
    // Error parsing type: , name: session
    // Error parsing type: , name: gameWatchdog
    // Error parsing type: , name: show
    // Error parsing type: , name: $__lazy_storage_$_drawerController
    // Error parsing type: , name: $__lazy_storage_$_broadcastViewController
    // Error parsing type: , name: $__lazy_storage_$_viewersContainerController
    // Error parsing type: , name: $__lazy_storage_$_gameController
}

- (void).cxx_destruct;
- (id)init;
- (void)rejoin;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words28WordsBroadcastViewController : UIViewController
{
    // Error parsing type: , name: session
    // Error parsing type: , name: resourceLoader
    // Error parsing type: , name: layoutConfiguration
    // Error parsing type: , name: show
    // Error parsing type: , name: isUserInteractionEnabled
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: systemKeyboardChangedHeight
    // Error parsing type: , name: $__lazy_storage_$_fullscreenRenderer
    // Error parsing type: , name: $__lazy_storage_$_playerView
    // Error parsing type: , name: $__lazy_storage_$_contentView
    // Error parsing type: , name: $__lazy_storage_$_trayController
    // Error parsing type: , name: $__lazy_storage_$_keyboard
    // Error parsing type: , name: $__lazy_storage_$_gameView
    // Error parsing type: , name: $__lazy_storage_$_dismissChatButton
    // Error parsing type: , name: $__lazy_storage_$_blurView
    // Error parsing type: , name: $__lazy_storage_$_dismissView
    // Error parsing type: , name: $__lazy_storage_$_loadingView
    // Error parsing type: , name: contentBottomConstraint
    // Error parsing type: , name: contentTopConstraint
    // Error parsing type: , name: trayHiddenTopConstraint
    // Error parsing type: , name: trayShowingBottomConstraint
    // Error parsing type: , name: trayHidden
    // Error parsing type: , name: dismissButtonConstraint
    // Error parsing type: , name: gameContentBottomConstraint
    // Error parsing type: , name: delegate
    // Error parsing type: , name: gameViewConstraint
    // Error parsing type: , name: showDismissKeyboardButton
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)onDismissKeyboardTap;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, readonly) long long preferredStatusBarStyle;

@end

@interface _TtC5Words32WinnersListYellowCircleAnimation : UIView <SLCoreAnimationBuildDelegate>
{
    // Error parsing type: , name: shouldPlayOut
    // Error parsing type: , name: state
    // Error parsing type: , name: onDone
    // Error parsing type: , name: yCoverage
    // Error parsing type: , name: ani
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)squallCoreAnimation:(id)arg1 willBuildAnimationsForLayer:(id)arg2 withName:(id)arg3;
- (void)squallCoreAnimationDidLayoutAnimationLayers:(id)arg1;

@end

@interface _TtC5Words29EliminatedModalViewController : _$s5HQKit5ModalCN
{
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: eliminationRound
    // Error parsing type: , name: totalAnswers
    // Error parsing type: , name: $__lazy_storage_$_dotViews
    // Error parsing type: , name: solidColorImage
    // Error parsing type: , name: $__lazy_storage_$_progressView
    // Error parsing type: , name: $__lazy_storage_$_avatarView
    // Error parsing type: , name: $__lazy_storage_$_headerLabel
    // Error parsing type: , name: $__lazy_storage_$_continueButton
}

- (void).cxx_destruct;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end

@interface _TtC5Words19WordsLiveResultsBar : UIView
{
    // Error parsing type: , name: $__lazy_storage_$_shapeLayer
    // Error parsing type: , name: $__lazy_storage_$_maskLayer
    // Error parsing type: , name: $__lazy_storage_$_borderLayer
    // Error parsing type: , name: style
    // Error parsing type: , name: percentage
    // Error parsing type: , name: $__lazy_storage_$_formatter
    // Error parsing type: , name: number
    // Error parsing type: , name: $__lazy_storage_$_label
    // Error parsing type: , name: $__lazy_storage_$_countLabel
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)traitCollectionDidChange:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words15WordsRoundScene : _TtC5Words5Scene
{
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: initialSolvedVolumeSubject
    // Error parsing type: , name: initialThinkingVolumeSubject
    // Error parsing type: , name: puzzleSolvedSubject
    // Error parsing type: , name: strikeoutSubject
    // Error parsing type: , name: presenter
    // Error parsing type: , name: controller
    // Error parsing type: , name: show
    // Error parsing type: , name: keyboard
    // Error parsing type: , name: roundId
    // Error parsing type: , name: gameInfo
    // Error parsing type: , name: layoutConfiguration
    // Error parsing type: , name: gameWatchdog
    // Error parsing type: , name: hasStarted
    // Error parsing type: , name: solvedEffect
    // Error parsing type: , name: thinkingEffect
    // Error parsing type: , name: puzzleGameState
    // Error parsing type: , name: $__lazy_storage_$_revealEventEmitter
    // Error parsing type: , name: startRoundMessage
    // Error parsing type: , name: roundEndTime
    // Error parsing type: , name: wordsRoundView
    // Error parsing type: , name: results
    // Error parsing type: , name: currentEvent
    // Error parsing type: , name: $__lazy_storage_$_tracker
    // Error parsing type: , name: $__lazy_storage_$_feedbackGenerator
}

- (void).cxx_destruct;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words15CirclePulseView : UIView
{
    // Error parsing type: , name: $__lazy_storage_$_circles
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words13WordsGameView : UIView
{
    // Error parsing type: , name: backgroundView
    // Error parsing type: , name: $__lazy_storage_$_bubbleView
    // Error parsing type: , name: $__lazy_storage_$_infoBar
    // Error parsing type: , name: $__lazy_storage_$_questionPlaceholderView
    // Error parsing type: , name: $__lazy_storage_$_bubbleManager
    // Error parsing type: , name: layoutConfiguration
    // Error parsing type: , name: fullscreenContainer
    // Error parsing type: , name: currentBuffer
    // Error parsing type: , name: bubbleGuide
    // Error parsing type: , name: displayTargets
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words24WordsLayoutConfiguration : _$s5HQKit19LayoutConfigurationCN
{
}

- (id)init;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words15WordsLetterView : UIView
{
    // Error parsing type: , name: tileAspectRatio
    // Error parsing type: , name: puzzle
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words20WordsLiveResultsView : UIView
{
    // Error parsing type: , name: $__lazy_storage_$_barEliminated
    // Error parsing type: , name: $__lazy_storage_$_barSolved
    // Error parsing type: , name: $__lazy_storage_$_barSolving
    // Error parsing type: , name: $__lazy_storage_$_stackView
}

- (void).cxx_destruct;
- (void)traitCollectionDidChange:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

@interface _TtC5WordsP33_F88705595A7F8DF3503FCFA3AF54B75711BundleClass : _TtCs12_SwiftObject
{
}

@end

@interface _TtC5Words21WordsLetterWheelImage : _TtCs12_SwiftObject
{
}

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words16WordsPointBubble : UIView
{
    // Error parsing type: , name: $__lazy_storage_$_msgLabel
    // Error parsing type: , name: points
    // Error parsing type: , name: style
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;

@end

@interface _TtC5Words27WordsRoundStatisticsTracker : _TtCs12_SwiftObject
{
    // Error parsing type: , name: show
    // Error parsing type: , name: gameWatchdog
    // Error parsing type: , name: guesses
    // Error parsing type: , name: startRound
    // Error parsing type: , name: hasGuessed
    // Error parsing type: , name: timesUp
    // Error parsing type: , name: playerState
}

@end

@interface _TtC5Words26WinnersListCircleAnimation : UIView
{
    // Error parsing type: , name: ani
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words21LabelLayoutTransition : NSObject
{
    // Error parsing type: , name: labelA
    // Error parsing type: , name: labelB
}

- (void).cxx_destruct;
- (id)init;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words19WordsGameController : NSObject
{
    // Error parsing type: , name: dependencies
    // Error parsing type: , name: session
    // Error parsing type: , name: delegate
    // Error parsing type: , name: show
    // Error parsing type: , name: keyboard
    // Error parsing type: , name: layoutConfiguration
    // Error parsing type: , name: configuration
    // Error parsing type: , name: viewController
    // Error parsing type: , name: drawerController
    // Error parsing type: , name: viewerSession
    // Error parsing type: , name: $__lazy_storage_$_stateManager
    // Error parsing type: , name: gameWatchdog
    // Error parsing type: , name: joining
    // Error parsing type: , name: ending
    // Error parsing type: , name: gameInfo
    // Error parsing type: , name: latestEndRound
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: $__lazy_storage_$_feedbackGenerator
    // Error parsing type: , name: $__lazy_storage_$_feedbackGeneratorImpact
    // Error parsing type: , name: inviteCoordinator
    // Error parsing type: , name: inviteSourceCard
    // Error parsing type: , name: didSelectProductSubject
    // Error parsing type: , name: onModalPresentSubject
    // Error parsing type: , name: $__lazy_storage_$_modalController
}

- (void).cxx_destruct;
- (id)init;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words23SuperWheelContainerView : UIView <AVAudioPlayerDelegate, CAAnimationDelegate>
{
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: wheelView
    // Error parsing type: , name: superWheelView
    // Error parsing type: , name: onCompletion
    // Error parsing type: , name: onWheelWillHide
    // Error parsing type: , name: wheelsContainerView
    // Error parsing type: , name: wheelWrapperView
    // Error parsing type: , name: letterTileStackView
    // Error parsing type: , name: wheelPanSubject
    // Error parsing type: , name: autoSpinSubject
    // Error parsing type: , name: spinCompleteSubject
    // Error parsing type: , name: wheelDataSubject
    // Error parsing type: , name: show
    // Error parsing type: , name: players
    // Error parsing type: , name: wheelData
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(_Bool)arg2;
- (void)didPanWithGesture:(id)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words9WheelView : UIView
{
    // Error parsing type: , name: segmentViews
    // Error parsing type: , name: diameter
    // Error parsing type: , name: segmentData
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words16WheelSegmentView : UIView
{
    // Error parsing type: , name: data
    // Error parsing type: , name: radius
    // Error parsing type: , name: degrees
    // Error parsing type: , name: backgroundShapeLayer
    // Error parsing type: , name: tileView
    // Error parsing type: , name: tileLabel
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words8TileView : UIView
{
    // Error parsing type: , name: letterTileView
    // Error parsing type: , name: questionMarkTileView
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words16WheelNumberBadge : UIView
{
    // Error parsing type: , name: label
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words14WordsStrikeDot : UIView
{
    // Error parsing type: , name: state
    // Error parsing type: , name: $__lazy_storage_$_xLegA
    // Error parsing type: , name: $__lazy_storage_$_xLegB
    // Error parsing type: , name: inactiveScale
    // Error parsing type: , name: diameter
    // Error parsing type: , name: lineThickness
    // Error parsing type: , name: xColor
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words20WordsRoundWinnerCell : UICollectionViewCell
{
    // Error parsing type: , name: style
    // Error parsing type: , name: avatarUrl
    // Error parsing type: , name: $__lazy_storage_$_indexLabel
    // Error parsing type: , name: $__lazy_storage_$_nameLabel
    // Error parsing type: , name: $__lazy_storage_$_pointsLabel
    // Error parsing type: , name: $__lazy_storage_$_pointsBackground
    // Error parsing type: , name: $__lazy_storage_$_backgroundPill
    // Error parsing type: , name: $__lazy_storage_$_imageView
    // Error parsing type: , name: $__lazy_storage_$_divider
    // Error parsing type: , name: name
    // Error parsing type: , name: index
    // Error parsing type: , name: points
    // Error parsing type: , name: pointsConstraint
    // Error parsing type: , name: imageConstraint
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)traitCollectionDidChange:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words13AnimatedLabel : UILabel
{
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: hiddenSizingLabel
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words12StarRingView : UIView <CAAnimationDelegate>
{
    // Error parsing type: , name: animationCompletion
    // Error parsing type: , name: circleThickness
    // Error parsing type: , name: $__lazy_storage_$_backgroundRingLayer
    // Error parsing type: , name: $__lazy_storage_$_fillRingLayer
    // Error parsing type: , name: $__lazy_storage_$_ringImageView
    // Error parsing type: , name: percentage
    // Error parsing type: , name: progressColor
    // Error parsing type: , name: ringColor
}

- (void).cxx_destruct;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words25WordsRoundWinnerLevelView : UIView
{
    // Error parsing type: , name: letterPointsValueLabel
    // Error parsing type: , name: timeBonusValueLabel
    // Error parsing type: , name: solvedPointsValueLabel
    // Error parsing type: , name: levelLabel
    // Error parsing type: , name: ringView
    // Error parsing type: , name: audioPlayer
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words16WordsResultsView : UIView
{
    // Error parsing type: , name: $__lazy_storage_$_tally
    // Error parsing type: , name: tallyStandin
    // Error parsing type: , name: resultsStandin
    // Error parsing type: , name: $__lazy_storage_$_label
    // Error parsing type: , name: $__lazy_storage_$_puzzle
    // Error parsing type: , name: $__lazy_storage_$_resultsView
    // Error parsing type: , name: $__lazy_storage_$_resultsLevelView
    // Error parsing type: , name: $__lazy_storage_$_resultsContainer
    // Error parsing type: , name: $__lazy_storage_$_mainStack
    // Error parsing type: , name: puzzleState
    // Error parsing type: , name: roundTime
    // Error parsing type: , name: layoutConfiguration
    // Error parsing type: , name: bubbleGuide
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words26WordsWinnersListHeaderView : UIView
{
    // Error parsing type: , name: onUpdate
    // Error parsing type: , name: onReuse
    // Error parsing type: , name: currentItems
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: playerViews
    // Error parsing type: , name: $__lazy_storage_$_contentStack
    // Error parsing type: , name: $__lazy_storage_$_winnerText
    // Error parsing type: , name: $__lazy_storage_$_winnerBackground
    // Error parsing type: , name: $__lazy_storage_$_circleAnimation
    // Error parsing type: , name: cells
    // Error parsing type: , name: animated
    // Error parsing type: , name: narrowDesign
}

- (void).cxx_destruct;
- (void)traitCollectionDidChange:(id)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words14WordsRoundView : UIView
{
    // Error parsing type: , name: state
    // Error parsing type: , name: round
    // Error parsing type: , name: $__lazy_storage_$_puzzleView
    // Error parsing type: , name: $__lazy_storage_$_rollOverStrikesView
    // Error parsing type: , name: $__lazy_storage_$_labelBig
    // Error parsing type: , name: $__lazy_storage_$_labelSmall
    // Error parsing type: , name: $__lazy_storage_$_gameContentContainer
    // Error parsing type: , name: $__lazy_storage_$_bottomContentContainer
    // Error parsing type: , name: $__lazy_storage_$_liveResultsContainer
    // Error parsing type: , name: $__lazy_storage_$_labelSmallContainer
    // Error parsing type: , name: keyboard
    // Error parsing type: , name: liveResults
    // Error parsing type: , name: gameStarted
    // Error parsing type: , name: delegate
    // Error parsing type: , name: intermediateOffsetYConstraint
    // Error parsing type: , name: labelTransitionTimer
    // Error parsing type: , name: liveResultsTimer
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: recentStats
    // Error parsing type: , name: layoutConfiguration
    // Error parsing type: , name: bubbleGuide
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, readonly) _Bool canBecomeFirstResponder;
- (id)initWithCoder:(id)arg1;
- (void)layoutSubviews;
- (void)traitCollectionDidChange:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words18WordsRoundHostView : UIView
{
    // Error parsing type: , name: $__lazy_storage_$_bufferLayer
    // Error parsing type: , name: $__lazy_storage_$_maskLayer
    // Error parsing type: , name: circleRadius
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words5Scene : NSObject
{
    // Error parsing type: , name: reacting
    // Error parsing type: , name: dismissing
    // Error parsing type: , name: completed
    // Error parsing type: , name: onDidReact
    // Error parsing type: , name: eventPresenter
}

- (void).cxx_destruct;
- (id)init;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words12WordsToolTip : UIView
{
    // Error parsing type: , name: kScale
    // Error parsing type: , name: kRot
    // Error parsing type: , name: kTrans
    // Error parsing type: , name: kWidth
    // Error parsing type: , name: kOpacity
    // Error parsing type: , name: $__lazy_storage_$_container
    // Error parsing type: , name: $__lazy_storage_$_positionCorrectionContainer
    // Error parsing type: , name: $__lazy_storage_$_tip
    // Error parsing type: , name: $__lazy_storage_$_mainBackground
    // Error parsing type: , name: $__lazy_storage_$_label
    // Error parsing type: , name: strikesLeft
}

- (void).cxx_destruct;
- (void)traitCollectionDidChange:(id)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words30WordsNearbyLetterHighlightView : UIView
{
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: roundView
    // Error parsing type: , name: avatarUrl
    // Error parsing type: , name: background
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words35WordsWinnersListPlayerTableViewCell : UITableViewCell
{
    // Error parsing type: , name: onUpdate
    // Error parsing type: , name: onReuse
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: item
    // Error parsing type: , name: $__lazy_storage_$_rankLabel
    // Error parsing type: , name: avatarImageView
    // Error parsing type: , name: divider
    // Error parsing type: , name: showRankAndTime
    // Error parsing type: , name: $__lazy_storage_$_nameLabel
    // Error parsing type: , name: $__lazy_storage_$_timeLabel
    // Error parsing type: , name: $__lazy_storage_$_spacer
    // Error parsing type: , name: $__lazy_storage_$_prizeCapsuleView
    // Error parsing type: , name: $__lazy_storage_$_leadingStack
}

- (void).cxx_destruct;
- (void)traitCollectionDidChange:(id)arg1;
- (void)prepareForReuse;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words15WordsBubbleView : UIView
{
    // Error parsing type: , name: provideHapticTimerTicks
    // Error parsing type: , name: timer
    // Error parsing type: , name: context
    // Error parsing type: , name: feedbackGenerator
    // Error parsing type: , name: $__lazy_storage_$_backgroundView
    // Error parsing type: , name: $__lazy_storage_$_videoContainer
    // Error parsing type: , name: appObserver
    // Error parsing type: , name: layoutConfiguration
    // Error parsing type: , name: fullscreenContainer
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words34WordsBubbleViewSizeChangeAnimation : _$s5HQKit13ViewAnimationCN
{
    // Error parsing type: , name: toCircle
    // Error parsing type: , name: bubbleView
    // Error parsing type: , name: videoContainerAnimation
    // Error parsing type: , name: oversizedBubble
}

- (void).cxx_destruct;
- (id)init;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words18AnimatedLabelQueue : UIView
{
    // Error parsing type: , name: running
    // Error parsing type: , name: commands
    // Error parsing type: , name: $__lazy_storage_$_labelA
    // Error parsing type: , name: $__lazy_storage_$_labelB
    // Error parsing type: , name: labelAIsActive
    // Error parsing type: , name: textColor
    // Error parsing type: , name: font
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words25WordsBubbleBackgroundView : UIView
{
    // Error parsing type: , name: kOpacityAnimation
    // Error parsing type: , name: kCountdownAnimation
    // Error parsing type: , name: $__lazy_storage_$_ringLayerUnder
    // Error parsing type: , name: $__lazy_storage_$_ringLayer
    // Error parsing type: , name: configuration
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;

@end

@interface _TtC5Words30WinnersListBlueCircleAnimation : UIView <SLCoreAnimationBuildDelegate>
{
    // Error parsing type: , name: shouldPlayOut
    // Error parsing type: , name: state
    // Error parsing type: , name: onDone
    // Error parsing type: , name: ani
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)squallCoreAnimation:(id)arg1 willBuildAnimationsForLayer:(id)arg2 withName:(id)arg3;
- (void)squallCoreAnimationDidLayoutAnimationLayers:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words29WordsWinnersListTopPlayerView : UIView
{
    // Error parsing type: , name: largeAvatar
    // Error parsing type: , name: $__lazy_storage_$_rankView
    // Error parsing type: , name: rank
    // Error parsing type: , name: avatarImageView
    // Error parsing type: , name: $__lazy_storage_$_nameLabel
    // Error parsing type: , name: $__lazy_storage_$_timeLabel
    // Error parsing type: , name: $__lazy_storage_$_prizeCapsuleView
    // Error parsing type: , name: $__lazy_storage_$_imageSpacerView
    // Error parsing type: , name: $__lazy_storage_$_nameSpacerView
    // Error parsing type: , name: nameLabelHeightConstraint
    // Error parsing type: , name: nameBufferSpace
    // Error parsing type: , name: $__lazy_storage_$_contentStack
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

@interface _TtC5Words21WonExtraLifeAnimation : UIView <SLCoreAnimationBuildDelegate>
{
    // Error parsing type: , name: onDone
    // Error parsing type: , name: avatarSize
    // Error parsing type: , name: heartTargetBounds
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: avatarMultiplier
    // Error parsing type: , name: aniHeart
    // Error parsing type: , name: avatarImage
}

- (void).cxx_destruct;
- (void)squallCoreAnimation:(id)arg1 willBuildAnimationsForLayer:(id)arg2 withName:(id)arg3;
- (void)squallCoreAnimationDidLayoutAnimationLayers:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words12WordsInfoBar : UIView
{
    // Error parsing type: , name: style
    // Error parsing type: , name: onUserList
    // Error parsing type: , name: onClose
    // Error parsing type: , name: userCount
    // Error parsing type: , name: points
    // Error parsing type: , name: $__lazy_storage_$_userIcon
    // Error parsing type: , name: $__lazy_storage_$_pointsLabel
    // Error parsing type: , name: $__lazy_storage_$_logoButton
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)pressedUser;
- (void)pressedClose;
- (void)traitCollectionDidChange:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words14ExtraLifeScene : _TtC5Words5Scene
{
    // Error parsing type: , name: presenter
    // Error parsing type: , name: controller
    // Error parsing type: , name: show
    // Error parsing type: , name: fullscreenContainer
    // Error parsing type: , name: extraLifeAnimation
    // Error parsing type: , name: isRunning
}

- (void).cxx_destruct;

@end

@interface _TtC5Words19WordsPuzzleLayouter : _TtCs12_SwiftObject
{
    // Error parsing type: , name: maxLines
    // Error parsing type: , name: tileAspectRatio
    // Error parsing type: , name: paddingX
    // Error parsing type: , name: paddingY
}

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words12KeyHighlight : UIView
{
    // Error parsing type: , name: $__lazy_storage_$_shape
    // Error parsing type: , name: $__lazy_storage_$_label
    // Error parsing type: , name: cornerRadius
    // Error parsing type: , name: color
    // Error parsing type: , name: character
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)traitCollectionDidChange:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words15WordsLetterTile : UIView
{
    // Error parsing type: , name: kBackgroundColorAnimation
    // Error parsing type: , name: kBorderAnimation
    // Error parsing type: , name: kScaleAnimation
    // Error parsing type: , name: kOpacityAnimation
    // Error parsing type: , name: kFlipAnimation
    // Error parsing type: , name: clearTimer
    // Error parsing type: , name: isRevealed
    // Error parsing type: , name: locked
    // Error parsing type: , name: container
    // Error parsing type: , name: burst
    // Error parsing type: , name: $__lazy_storage_$_label
    // Error parsing type: , name: style
    // Error parsing type: , name: character
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words18WordsTimeCountdown : UIView
{
    // Error parsing type: , name: totalTime
    // Error parsing type: , name: time
    // Error parsing type: , name: timeAnimation
    // Error parsing type: , name: $__lazy_storage_$_label
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words19RolloverStrikesView : UIView
{
    // Error parsing type: , name: strikeCount
    // Error parsing type: , name: extraStrikeCount
    // Error parsing type: , name: strikeLabel
    // Error parsing type: , name: extraStrikesLabel
    // Error parsing type: , name: strikesCountainerView
    // Error parsing type: , name: extraStrikesCountainerView
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words21WordsGameStateManager : NSObject
{
    // Error parsing type: , name: watchDog
    // Error parsing type: , name: backgroundEvent
    // Error parsing type: , name: backgrounded
    // Error parsing type: , name: locked
    // Error parsing type: , name: events
    // Error parsing type: , name: currentScene
    // Error parsing type: , name: delegate
}

- (void).cxx_destruct;
- (id)init;
- (void)applicationDidEnterBackground;
- (void)applicationWillEnterForeground;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words25WordsBubbleVideoContainer : UIView
{
    // Error parsing type: , name: $__lazy_storage_$_videoView
    // Error parsing type: , name: $__lazy_storage_$_playerView
    // Error parsing type: , name: $__lazy_storage_$_maskLayer
    // Error parsing type: , name: $__lazy_storage_$_borderCircle
    // Error parsing type: , name: layoutConfiguration
    // Error parsing type: , name: fullscreenContainer
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words33WordsBubbleContainerViewAnimation : _$s5HQKit13ViewAnimationCN
{
    // Error parsing type: , name: kAniMask
    // Error parsing type: , name: kAniMaskPosition
    // Error parsing type: , name: kAniBorder
    // Error parsing type: , name: kAniBorderWidth
    // Error parsing type: , name: kAniScale
    // Error parsing type: , name: kAniSuperviewScale
    // Error parsing type: , name: kAniPosition
    // Error parsing type: , name: layer
    // Error parsing type: , name: borderCircle
    // Error parsing type: , name: maskLayer
    // Error parsing type: , name: superLayer
    // Error parsing type: , name: toCircle
    // Error parsing type: , name: oversizedBubble
    // Error parsing type: , name: videoBounds
    // Error parsing type: , name: borderThickness
    // Error parsing type: , name: screenBounds
    // Error parsing type: , name: layoutConfiguration
    // Error parsing type: , name: rootLayer
}

- (void).cxx_destruct;
- (id)init;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words15WordsPuzzleView : UIView
{
    // Error parsing type: , name: $__lazy_storage_$_layouter
    // Error parsing type: , name: puzzleContainer
    // Error parsing type: , name: tiles
    // Error parsing type: , name: puzzle
    // Error parsing type: , name: currentLayout
    // Error parsing type: , name: locked
    // Error parsing type: , name: delegate
    // Error parsing type: , name: scalePuzzleOnLayout
    // Error parsing type: , name: tileBoundsGuide
    // Error parsing type: , name: tileBoundsBottomConstraint
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words24WordsRoundUserWinnerCell : UICollectionViewCell
{
    // Error parsing type: , name: avatarUrl
    // Error parsing type: , name: $__lazy_storage_$_midStack
    // Error parsing type: , name: $__lazy_storage_$_midStackContainer
    // Error parsing type: , name: $__lazy_storage_$_msgLabel
    // Error parsing type: , name: $__lazy_storage_$_rankLabel
    // Error parsing type: , name: $__lazy_storage_$_pointsLabel
    // Error parsing type: , name: $__lazy_storage_$_pointsBackground
    // Error parsing type: , name: $__lazy_storage_$_backgroundPill
    // Error parsing type: , name: $__lazy_storage_$_imageView
    // Error parsing type: , name: userWasCorrect
    // Error parsing type: , name: rank
    // Error parsing type: , name: points
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words18WordsBubbleManager : NSObject
{
    // Error parsing type: , name: $__lazy_storage_$_stateManager
    // Error parsing type: , name: view
    // Error parsing type: , name: bubbleView
    // Error parsing type: , name: oversizedBubble
    // Error parsing type: , name: layoutConfiguration
}

- (void).cxx_destruct;
- (id)init;

@end

@interface _TtC5Words19WordsLetterSpinView : UIView
{
    // Error parsing type: , name: kRotationAni
    // Error parsing type: , name: kDisplayHighlightAni
    // Error parsing type: , name: kMinVelocity
    // Error parsing type: , name: letters
    // Error parsing type: , name: monitorAnimation
    // Error parsing type: , name: highlightWidthConstraint
    // Error parsing type: , name: feedbackGenerator
    // Error parsing type: , name: state
    // Error parsing type: , name: $__lazy_storage_$_wheel
    // Error parsing type: , name: $__lazy_storage_$_wheelContainer
    // Error parsing type: , name: $__lazy_storage_$_wheelMask
    // Error parsing type: , name: $__lazy_storage_$_spinDisplayContainer
    // Error parsing type: , name: $__lazy_storage_$_letterLabel
    // Error parsing type: , name: $__lazy_storage_$_labelContainer
    // Error parsing type: , name: $__lazy_storage_$_label
    // Error parsing type: , name: rootContainer
    // Error parsing type: , name: wheelConstraint
    // Error parsing type: , name: onWillSpinLetter
    // Error parsing type: , name: onDidSpinLetter
}

- (void).cxx_destruct;
- (void)onPanWithPan:(id)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

@interface _TtC5Words17WordsKeyboardView : UIView
{
    // Error parsing type: , name: keys
    // Error parsing type: , name: $__lazy_storage_$_layouter
    // Error parsing type: , name: locked
    // Error parsing type: , name: state
    // Error parsing type: , name: $__lazy_storage_$_keyContainer
    // Error parsing type: , name: $__lazy_storage_$_keyHighlightContainer
    // Error parsing type: , name: tiles
    // Error parsing type: , name: currentLayout
    // Error parsing type: , name: $__lazy_storage_$_keyHighlight
    // Error parsing type: , name: delegate
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)dealloc;
- (void)willMoveToSuperview:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words20WordsLetterSpinScene : _TtC5Words5Scene
{
    // Error parsing type: , name: $__lazy_storage_$_backgroundView
    // Error parsing type: , name: $__lazy_storage_$_hostView
    // Error parsing type: , name: $__lazy_storage_$_hostHlsView
    // Error parsing type: , name: $__lazy_storage_$_videoView
    // Error parsing type: , name: $__lazy_storage_$_superWheelView
    // Error parsing type: , name: show
    // Error parsing type: , name: layoutConfiguration
    // Error parsing type: , name: presenter
    // Error parsing type: , name: controller
    // Error parsing type: , name: fullscreenView
    // Error parsing type: , name: viewerSession
}

- (void).cxx_destruct;
- (void)dealloc;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words26SuperWheelSceneWrapperView : UIView
{
    // Error parsing type: , name: wheelContainer
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words15WordsStrikeView : UIView
{
    // Error parsing type: , name: $__lazy_storage_$_tooltip
    // Error parsing type: , name: strikes
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

@interface _TtC5Words20WordsRoundWinnerView : UIView
{
    // Error parsing type: , name: avatarImageView
    // Error parsing type: , name: $__lazy_storage_$_starStack
    // Error parsing type: , name: $__lazy_storage_$_starViews
    // Error parsing type: , name: $__lazy_storage_$_middleStack
    // Error parsing type: , name: $__lazy_storage_$_mainStack
    // Error parsing type: , name: statsContainer
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: $__lazy_storage_$_nameLabel
    // Error parsing type: , name: $__lazy_storage_$_roundLabel
    // Error parsing type: , name: $__lazy_storage_$_timeCountdown
    // Error parsing type: , name: name
    // Error parsing type: , name: endRound
    // Error parsing type: , name: soundTimer
    // Error parsing type: , name: winnerEffect
    // Error parsing type: , name: totalTime
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;

@end

@interface _TtC5Words18WordsStarAnimation : UIView <SLCoreAnimationBuildDelegate>
{
    // Error parsing type: , name: animation
    // Error parsing type: , name: shouldPlay
    // Error parsing type: , name: onStart
    // Error parsing type: , name: timer
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)squallCoreAnimation:(id)arg1 willBuildAnimationsForLayer:(id)arg2 withName:(id)arg3;
- (void)squallCoreAnimationDidLayoutAnimationLayers:(id)arg1;
- (void)layoutSubviews;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words16WordsRevealTally : UIView
{
    // Error parsing type: , name: countFormatter
    // Error parsing type: , name: $__lazy_storage_$_incorrectLabel
    // Error parsing type: , name: $__lazy_storage_$_correctLabel
    // Error parsing type: , name: $__lazy_storage_$_checkMark
    // Error parsing type: , name: $__lazy_storage_$_cross
    // Error parsing type: , name: correctTally
    // Error parsing type: , name: incorrectTally
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words22WordsWinnerListYouView : UIView
{
    // Error parsing type: , name: avatarImageView
    // Error parsing type: , name: $__lazy_storage_$_timeLabels
    // Error parsing type: , name: $__lazy_storage_$_prizeLabels
    // Error parsing type: , name: $__lazy_storage_$_timeContainer
    // Error parsing type: , name: $__lazy_storage_$_prizeContainer
    // Error parsing type: , name: $__lazy_storage_$_trophy
    // Error parsing type: , name: $__lazy_storage_$_imageMiddleStack
    // Error parsing type: , name: $__lazy_storage_$_nameLabel
    // Error parsing type: , name: $__lazy_storage_$_button
    // Error parsing type: , name: onUpdate
    // Error parsing type: , name: onReuse
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: onShare
    // Error parsing type: , name: $__lazy_storage_$_circleAnimation
    // Error parsing type: , name: currentItem
}

- (void).cxx_destruct;
- (void)traitCollectionDidChange:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Words21WordsLetterPlayerView : UIView
{
    // Error parsing type: , name: $__lazy_storage_$_playerView
    // Error parsing type: , name: $__lazy_storage_$_maskLayer
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

