//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark -

//
// File: Payload/HQ-iOS.app/Frameworks/HQStyle.framework/HQStyle
// UUID: 81894496-89C8-3C88-A0BF-4E2110EA9537
//
//                           Arch: arm64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 0.0.0.0.0
//
// Objective-C Garbage Collection: Unsupported
//
//                       Run path: /usr/lib/swift
//                               = /usr/lib/swift
//                       Run path: @executable_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQStyle.framework/Frameworks
//                       Run path: @loader_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQStyle.framework/Frameworks
//

@interface _TtC7HQStyleP33_10A526DE11548FAF20C976E1C2B8F6AD11BundleClass : _TtCs12_SwiftObject
{
}

@end

@interface _TtC7HQStyleP33_C5038E6448976CDD325B44EF9614C41011BundleClass : _TtCs12_SwiftObject
{
}

@end

