//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark -

//
// File: Payload/HQ-iOS.app/Frameworks/HQAnalytics.framework/HQAnalytics
// UUID: 44061A46-301F-3293-8E49-E8234FC2E536
//
//                           Arch: arm64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 0.0.0.0.0
//
// Objective-C Garbage Collection: Unsupported
//
//                       Run path: /usr/lib/swift
//                               = /usr/lib/swift
//                       Run path: @executable_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQAnalytics.framework/Frameworks
//                       Run path: @loader_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQAnalytics.framework/Frameworks
//                       Run path: @executable_path/../../Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQAnalytics.framework/../../Frameworks
//                       Run path: @executable_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQAnalytics.framework/Frameworks
//                       Run path: @loader_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQAnalytics.framework/Frameworks
//

@interface _TtC11HQAnalytics12GameWatchdog : NSObject
{
    // Error parsing type: , name: eventQueue
    // Error parsing type: , name: events
    // Error parsing type: , name: fileManager
    // Error parsing type: , name: generatorPlugins
    // Error parsing type: , name: logId
    // Error parsing type: , name: $__lazy_storage_$_persister
}

- (void).cxx_destruct;
- (id)init;

@end

@interface _TtC11HQAnalyticsP33_A5950295AFB0674C612973D7FD57A2A613TelemetryImpl : _TtCs12_SwiftObject
{
    // Error parsing type: , name: MAX_QUEUE_SIZE
    // Error parsing type: , name: timer
    // Error parsing type: , name: telemetryLogEventQueue
    // Error parsing type: , name: telemetryTrackEventQueue
    // Error parsing type: , name: eventQueue
    // Error parsing type: , name: triggerTelemetryLogBatch
    // Error parsing type: , name: triggerTelemetryTrackBatch
    // Error parsing type: , name: configuration
    // Error parsing type: , name: telemetryConfigurationSet
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: $__lazy_storage_$_scheduler
}

- (void)execute;

@end

@interface _TtC11HQAnalytics31GameWatchdogFilePersisterPlugin : _TtCs12_SwiftObject
{
    // Error parsing type: , name: $__lazy_storage_$_timestampFormatter
    // Error parsing type: , name: fileManager
}

@end

@interface _TtC11HQAnalytics30GameWatchdogAppLifecyclePlugin : NSObject
{
    // Error parsing type: , name: onEvent
}

- (void).cxx_destruct;
- (id)init;
- (void)didReceiveMemoryWarningWithNotification:(id)arg1;
- (void)willResignActiveWithNotification:(id)arg1;
- (void)didBecomeActiveWithNotification:(id)arg1;
- (void)willEnterForegroundWithNotification:(id)arg1;
- (void)didEnterBackgroundWithNotification:(id)arg1;

@end

@interface _TtC11HQAnalyticsP33_31F9AB47FEFD47209703B3A270614C6716_AnalyticService : _TtCs12_SwiftObject
{
    // Error parsing type: , name: defaultMetadata
    // Error parsing type: , name: session
}

@end

