//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark Named Structures

struct CGPoint {
    double _field1;
    double _field2;
};

struct CGRect {
    struct CGPoint _field1;
    struct CGSize _field2;
};

struct CGSize {
    double _field1;
    double _field2;
};

struct _NSRange {
    unsigned long long _field1;
    unsigned long long _field2;
};

#pragma mark Typedef'd Structures

typedef struct {
    unsigned char _field1;
    unsigned char _field2;
    unsigned char _field3;
    unsigned char _field4;
} CDStruct_a06f635e;

typedef struct {
    unsigned long long _field1;
    unsigned long long _field2;
    unsigned long long _field3;
} CDStruct_14f26992;

typedef struct {
    CDStruct_14f26992 _field1;
    CDStruct_14f26992 _field2;
} CDStruct_4c83c94d;

#pragma mark -

//
// File: Payload/HQ-iOS.app/Frameworks/Jokes.framework/Jokes
// UUID: F623F20B-E537-3E56-BDFC-5D42950D338E
//
//                           Arch: arm64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 0.0.0.0.0
//
// Objective-C Garbage Collection: Unsupported
//
//                       Run path: /usr/lib/swift
//                               = /usr/lib/swift
//                       Run path: @executable_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/Jokes.framework/Frameworks
//                       Run path: @loader_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/Jokes.framework/Frameworks
//                       Run path: @executable_path/../../Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/Jokes.framework/../../Frameworks
//                       Run path: @executable_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/Jokes.framework/Frameworks
//                       Run path: @loader_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/Jokes.framework/Frameworks
//

@protocol MTLCommandQueue <NSObject>
- (void)insertDebugCaptureBoundary;
- (id <MTLCommandBuffer>)commandBufferWithUnretainedReferences;
- (id <MTLCommandBuffer>)commandBufferWithDescriptor:(MTLCommandBufferDescriptor *)arg1;
- (id <MTLCommandBuffer>)commandBuffer;
@property(nonatomic, readonly) id <MTLDevice> device;
@property(nonatomic, copy) NSString *label;
@end

@protocol MTLResource <NSObject>
- (_Bool)isAliasable;
- (void)makeAliasable;
@property(nonatomic, readonly) long long allocatedSize;
@property(nonatomic, readonly) long long heapOffset;
@property(nonatomic, readonly) id <MTLHeap> heap;
- (unsigned long long)setPurgeableState:(unsigned long long)arg1;
@property(nonatomic, readonly) unsigned long long resourceOptions;
@property(nonatomic, readonly) unsigned long long hazardTrackingMode;
@property(nonatomic, readonly) unsigned long long storageMode;
@property(nonatomic, readonly) unsigned long long cpuCacheMode;
@property(nonatomic, readonly) id <MTLDevice> device;
@property(nonatomic, copy) NSString *label;
@end

@protocol MTLTexture <MTLResource>
- (id <MTLTexture>)newTextureViewWithPixelFormat:(unsigned long long)arg1 textureType:(unsigned long long)arg2 levels:(struct _NSRange)arg3 slices:(struct _NSRange)arg4 swizzle:(CDStruct_a06f635e)arg5;
@property(nonatomic, readonly) CDStruct_a06f635e swizzle;
- (MTLSharedTextureHandle *)newSharedTextureHandle;
- (id <MTLTexture>)newTextureViewWithPixelFormat:(unsigned long long)arg1 textureType:(unsigned long long)arg2 levels:(struct _NSRange)arg3 slices:(struct _NSRange)arg4;
- (id <MTLTexture>)newTextureViewWithPixelFormat:(unsigned long long)arg1;
- (void)replaceRegion:(CDStruct_4c83c94d)arg1 mipmapLevel:(unsigned long long)arg2 withBytes:(const void *)arg3 bytesPerRow:(unsigned long long)arg4;
- (void)getBytes:(void *)arg1 bytesPerRow:(unsigned long long)arg2 fromRegion:(CDStruct_4c83c94d)arg3 mipmapLevel:(unsigned long long)arg4;
- (void)replaceRegion:(CDStruct_4c83c94d)arg1 mipmapLevel:(unsigned long long)arg2 slice:(unsigned long long)arg3 withBytes:(const void *)arg4 bytesPerRow:(unsigned long long)arg5 bytesPerImage:(unsigned long long)arg6;
- (void)getBytes:(void *)arg1 bytesPerRow:(unsigned long long)arg2 bytesPerImage:(unsigned long long)arg3 fromRegion:(CDStruct_4c83c94d)arg4 mipmapLevel:(unsigned long long)arg5 slice:(unsigned long long)arg6;
@property(nonatomic, readonly) long long compressionType;
@property(nonatomic, readonly) _Bool allowGPUOptimizedContents;
@property(nonatomic, readonly) _Bool isSparse;
@property(nonatomic, readonly) long long tailSizeInBytes;
@property(nonatomic, readonly) long long firstMipmapInTail;
- (_Bool)isFramebufferOnly;
- (_Bool)isShareable;
@property(nonatomic, readonly) unsigned long long usage;
@property(nonatomic, readonly) long long arrayLength;
@property(nonatomic, readonly) long long sampleCount;
@property(nonatomic, readonly) long long mipmapLevelCount;
@property(nonatomic, readonly) long long depth;
@property(nonatomic, readonly) long long height;
@property(nonatomic, readonly) long long width;
@property(nonatomic, readonly) unsigned long long pixelFormat;
@property(nonatomic, readonly) unsigned long long textureType;
@property(nonatomic, readonly) long long iosurfacePlane;
@property(nonatomic, readonly) struct __IOSurface *iosurface;
@property(nonatomic, readonly) long long bufferBytesPerRow;
@property(nonatomic, readonly) long long bufferOffset;
@property(nonatomic, readonly) id <MTLBuffer> buffer;
@property(nonatomic, readonly) long long parentRelativeSlice;
@property(nonatomic, readonly) long long parentRelativeLevel;
@property(nonatomic, readonly) id <MTLTexture> parentTexture;
@property(nonatomic, readonly) id <MTLResource> rootResource;

// Remaining properties
@property(nonatomic, readonly) _Bool framebufferOnly;
@property(nonatomic, readonly) _Bool shareable;
@end

@protocol NSObject
@property(nonatomic, readonly) NSString *description;
- (struct _NSZone *)zone;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (_Bool)respondsToSelector:(SEL)arg1;
- (_Bool)conformsToProtocol:(Protocol *)arg1;
- (_Bool)isMemberOfClass:(Class)arg1;
- (_Bool)isKindOfClass:(Class)arg1;
- (_Bool)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (id)self;
- (Class)class;
@property(nonatomic, readonly) Class superclass;
@property(nonatomic, readonly) long long hash;
- (_Bool)isEqual:(id)arg1;

@optional
@property(nonatomic, readonly) NSString *debugDescription;
@end

@protocol UIScrollViewDelegate <NSObject>

@optional
- (void)scrollViewDidChangeAdjustedContentInset:(UIScrollView *)arg1;
- (void)scrollViewDidScrollToTop:(UIScrollView *)arg1;
- (_Bool)scrollViewShouldScrollToTop:(UIScrollView *)arg1;
- (void)scrollViewDidEndZooming:(UIScrollView *)arg1 withView:(UIView *)arg2 atScale:(double)arg3;
- (void)scrollViewWillBeginZooming:(UIScrollView *)arg1 withView:(UIView *)arg2;
- (UIView *)viewForZoomingInScrollView:(UIScrollView *)arg1;
- (void)scrollViewDidEndScrollingAnimation:(UIScrollView *)arg1;
- (void)scrollViewDidEndDecelerating:(UIScrollView *)arg1;
- (void)scrollViewWillBeginDecelerating:(UIScrollView *)arg1;
- (void)scrollViewDidEndDragging:(UIScrollView *)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillEndDragging:(UIScrollView *)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewWillBeginDragging:(UIScrollView *)arg1;
- (void)scrollViewDidZoom:(UIScrollView *)arg1;
- (void)scrollViewDidScroll:(UIScrollView *)arg1;
@end

@protocol UITableViewDataSource <NSObject>
- (UITableViewCell *)tableView:(UITableView *)arg1 cellForRowAtIndexPath:(NSIndexPath *)arg2;
- (long long)tableView:(UITableView *)arg1 numberOfRowsInSection:(long long)arg2;

@optional
- (void)tableView:(UITableView *)arg1 moveRowAtIndexPath:(NSIndexPath *)arg2 toIndexPath:(NSIndexPath *)arg3;
- (void)tableView:(UITableView *)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(NSIndexPath *)arg3;
- (long long)tableView:(UITableView *)arg1 sectionForSectionIndexTitle:(NSString *)arg2 atIndex:(long long)arg3;
- (NSArray *)sectionIndexTitlesForTableView:(UITableView *)arg1;
- (_Bool)tableView:(UITableView *)arg1 canMoveRowAtIndexPath:(NSIndexPath *)arg2;
- (_Bool)tableView:(UITableView *)arg1 canEditRowAtIndexPath:(NSIndexPath *)arg2;
- (NSString *)tableView:(UITableView *)arg1 titleForFooterInSection:(long long)arg2;
- (NSString *)tableView:(UITableView *)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(UITableView *)arg1;
@end

@protocol UITableViewDelegate <NSObject, UIScrollViewDelegate>

@optional
- (void)tableView:(UITableView *)arg1 willEndContextMenuInteractionWithConfiguration:(UIContextMenuConfiguration *)arg2 animator:(id <UIContextMenuInteractionAnimating>)arg3;
- (void)tableView:(UITableView *)arg1 willDisplayContextMenuWithConfiguration:(UIContextMenuConfiguration *)arg2 animator:(id <UIContextMenuInteractionAnimating>)arg3;
- (void)tableView:(UITableView *)arg1 willPerformPreviewActionForMenuWithConfiguration:(UIContextMenuConfiguration *)arg2 animator:(id <UIContextMenuInteractionCommitAnimating>)arg3;
- (UITargetedPreview *)tableView:(UITableView *)arg1 previewForDismissingContextMenuWithConfiguration:(UIContextMenuConfiguration *)arg2;
- (UITargetedPreview *)tableView:(UITableView *)arg1 previewForHighlightingContextMenuWithConfiguration:(UIContextMenuConfiguration *)arg2;
- (UIContextMenuConfiguration *)tableView:(UITableView *)arg1 contextMenuConfigurationForRowAtIndexPath:(NSIndexPath *)arg2 point:(struct CGPoint)arg3;
- (void)tableViewDidEndMultipleSelectionInteraction:(UITableView *)arg1;
- (void)tableView:(UITableView *)arg1 didBeginMultipleSelectionInteractionAtIndexPath:(NSIndexPath *)arg2;
- (_Bool)tableView:(UITableView *)arg1 shouldBeginMultipleSelectionInteractionAtIndexPath:(NSIndexPath *)arg2;
- (_Bool)tableView:(UITableView *)arg1 shouldSpringLoadRowAtIndexPath:(NSIndexPath *)arg2 withContext:(id <UISpringLoadedInteractionContext>)arg3;
- (_Bool)tableView:(UITableView *)arg1 selectionFollowsFocusForRowAtIndexPath:(NSIndexPath *)arg2;
- (NSIndexPath *)indexPathForPreferredFocusedViewInTableView:(UITableView *)arg1;
- (void)tableView:(UITableView *)arg1 didUpdateFocusInContext:(UITableViewFocusUpdateContext *)arg2 withAnimationCoordinator:(UIFocusAnimationCoordinator *)arg3;
- (_Bool)tableView:(UITableView *)arg1 shouldUpdateFocusInContext:(UITableViewFocusUpdateContext *)arg2;
- (_Bool)tableView:(UITableView *)arg1 canFocusRowAtIndexPath:(NSIndexPath *)arg2;
- (void)tableView:(UITableView *)arg1 performAction:(SEL)arg2 forRowAtIndexPath:(NSIndexPath *)arg3 withSender:(id)arg4;
- (_Bool)tableView:(UITableView *)arg1 canPerformAction:(SEL)arg2 forRowAtIndexPath:(NSIndexPath *)arg3 withSender:(id)arg4;
- (_Bool)tableView:(UITableView *)arg1 shouldShowMenuForRowAtIndexPath:(NSIndexPath *)arg2;
- (long long)tableView:(UITableView *)arg1 indentationLevelForRowAtIndexPath:(NSIndexPath *)arg2;
- (NSIndexPath *)tableView:(UITableView *)arg1 targetIndexPathForMoveFromRowAtIndexPath:(NSIndexPath *)arg2 toProposedIndexPath:(NSIndexPath *)arg3;
- (void)tableView:(UITableView *)arg1 didEndEditingRowAtIndexPath:(NSIndexPath *)arg2;
- (void)tableView:(UITableView *)arg1 willBeginEditingRowAtIndexPath:(NSIndexPath *)arg2;
- (_Bool)tableView:(UITableView *)arg1 shouldIndentWhileEditingRowAtIndexPath:(NSIndexPath *)arg2;
- (UISwipeActionsConfiguration *)tableView:(UITableView *)arg1 trailingSwipeActionsConfigurationForRowAtIndexPath:(NSIndexPath *)arg2;
- (UISwipeActionsConfiguration *)tableView:(UITableView *)arg1 leadingSwipeActionsConfigurationForRowAtIndexPath:(NSIndexPath *)arg2;
- (NSArray *)tableView:(UITableView *)arg1 editActionsForRowAtIndexPath:(NSIndexPath *)arg2;
- (NSString *)tableView:(UITableView *)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(NSIndexPath *)arg2;
- (long long)tableView:(UITableView *)arg1 editingStyleForRowAtIndexPath:(NSIndexPath *)arg2;
- (void)tableView:(UITableView *)arg1 didDeselectRowAtIndexPath:(NSIndexPath *)arg2;
- (void)tableView:(UITableView *)arg1 didSelectRowAtIndexPath:(NSIndexPath *)arg2;
- (NSIndexPath *)tableView:(UITableView *)arg1 willDeselectRowAtIndexPath:(NSIndexPath *)arg2;
- (NSIndexPath *)tableView:(UITableView *)arg1 willSelectRowAtIndexPath:(NSIndexPath *)arg2;
- (void)tableView:(UITableView *)arg1 didUnhighlightRowAtIndexPath:(NSIndexPath *)arg2;
- (void)tableView:(UITableView *)arg1 didHighlightRowAtIndexPath:(NSIndexPath *)arg2;
- (_Bool)tableView:(UITableView *)arg1 shouldHighlightRowAtIndexPath:(NSIndexPath *)arg2;
- (void)tableView:(UITableView *)arg1 accessoryButtonTappedForRowWithIndexPath:(NSIndexPath *)arg2;
- (long long)tableView:(UITableView *)arg1 accessoryTypeForRowWithIndexPath:(NSIndexPath *)arg2;
- (UIView *)tableView:(UITableView *)arg1 viewForFooterInSection:(long long)arg2;
- (UIView *)tableView:(UITableView *)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(UITableView *)arg1 estimatedHeightForFooterInSection:(long long)arg2;
- (double)tableView:(UITableView *)arg1 estimatedHeightForHeaderInSection:(long long)arg2;
- (double)tableView:(UITableView *)arg1 estimatedHeightForRowAtIndexPath:(NSIndexPath *)arg2;
- (double)tableView:(UITableView *)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(UITableView *)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(UITableView *)arg1 heightForRowAtIndexPath:(NSIndexPath *)arg2;
- (void)tableView:(UITableView *)arg1 didEndDisplayingFooterView:(UIView *)arg2 forSection:(long long)arg3;
- (void)tableView:(UITableView *)arg1 didEndDisplayingHeaderView:(UIView *)arg2 forSection:(long long)arg3;
- (void)tableView:(UITableView *)arg1 didEndDisplayingCell:(UITableViewCell *)arg2 forRowAtIndexPath:(NSIndexPath *)arg3;
- (void)tableView:(UITableView *)arg1 willDisplayFooterView:(UIView *)arg2 forSection:(long long)arg3;
- (void)tableView:(UITableView *)arg1 willDisplayHeaderView:(UIView *)arg2 forSection:(long long)arg3;
- (void)tableView:(UITableView *)arg1 willDisplayCell:(UITableViewCell *)arg2 forRowAtIndexPath:(NSIndexPath *)arg3;
@end

@protocol UITextFieldDelegate <NSObject>

@optional
- (_Bool)textFieldShouldReturn:(UITextField *)arg1;
- (_Bool)textFieldShouldClear:(UITextField *)arg1;
- (void)textFieldDidChangeSelection:(UITextField *)arg1;
- (_Bool)textField:(UITextField *)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(NSString *)arg3;
- (void)textFieldDidEndEditing:(UITextField *)arg1 reason:(long long)arg2;
- (void)textFieldDidEndEditing:(UITextField *)arg1;
- (_Bool)textFieldShouldEndEditing:(UITextField *)arg1;
- (void)textFieldDidBeginEditing:(UITextField *)arg1;
- (_Bool)textFieldShouldBeginEditing:(UITextField *)arg1;
@end

__attribute__((visibility("hidden")))
@interface _TtC5Jokes16JokesMeterNeedle : UIView
{
    // Error parsing type: , name: rotationPublisher
    // Error parsing type: , name: feedbackGenerator
    // Error parsing type: , name: previousTemperature
    // Error parsing type: , name: nullDelegate
    // Error parsing type: , name: $__lazy_storage_$_needleLayer
    // Error parsing type: , name: $__lazy_storage_$_rotationAnimation
    // Error parsing type: , name: rotation
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) double rotation; // @synthesize rotation;

@end

@interface _TtC5Jokes23JokesGameViewController : UIViewController
{
    // Error parsing type: , name: fullScreenContentView
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: leaveButtonSubject
    // Error parsing type: , name: jokeSessionEnded
    // Error parsing type: , name: show
    // Error parsing type: , name: socket
    // Error parsing type: , name: presentCoinsAnimationSubject
    // Error parsing type: , name: $__lazy_storage_$_hlsPlayer
    // Error parsing type: , name: $__lazy_storage_$_coinBalance
    // Error parsing type: , name: $__lazy_storage_$_videoView
    // Error parsing type: , name: $__lazy_storage_$_blurEffectView
    // Error parsing type: , name: $__lazy_storage_$_logoButton
    // Error parsing type: , name: $__lazy_storage_$_userCountButton
    // Error parsing type: , name: $__lazy_storage_$_chatViewController
    // Error parsing type: , name: $__lazy_storage_$_transitionManager
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(nonatomic, readonly) long long preferredStatusBarStyle;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Jokes7TipView : UIView
{
    // Error parsing type: , name: $__lazy_storage_$_mainStack
    // Error parsing type: , name: $__lazy_storage_$_labels
    // Error parsing type: , name: $__lazy_storage_$_buffer
    // Error parsing type: , name: $__lazy_storage_$_avatar
    // Error parsing type: , name: $__lazy_storage_$_backgroundView
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: tip
    // Error parsing type: , name: tipAmount
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Jokes8TipSlots : UIView
{
    // Error parsing type: , name: inflightTips
    // Error parsing type: , name: tipPaddingY
    // Error parsing type: , name: tipHeight
    // Error parsing type: , name: addTips
    // Error parsing type: , name: addUserTipPublisher
    // Error parsing type: , name: animateOutPublisher
    // Error parsing type: , name: configPublisher
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: maxSlots
    // Error parsing type: , name: normalTipAmount
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

@interface _TtC5Jokes17JokesGradientView : UIView
{
}

+ (Class)layerClass;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Jokes20JokeMeterSectionView : UIView
{
    // Error parsing type: , name: $__lazy_storage_$_shapeColor
    // Error parsing type: , name: $__lazy_storage_$_maskLayer
    // Error parsing type: , name: nullDelegate
    // Error parsing type: , name: $__lazy_storage_$_middle
    // Error parsing type: , name: start
    // Error parsing type: , name: end
    // Error parsing type: , name: highlighted
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

@interface _TtC5Jokes19DynamicLabelWordMap : _TtCs12_SwiftObject
{
    // Error parsing type: , name: label
    // Error parsing type: , name: perUnitDelay
}

@end

__attribute__((visibility("hidden")))
@interface _TtC5Jokes10JokesMeter : UIView
{
    // Error parsing type: , name: $__lazy_storage_$_sectionsView
    // Error parsing type: , name: $__lazy_storage_$_body
    // Error parsing type: , name: $__lazy_storage_$_hotButton
    // Error parsing type: , name: $__lazy_storage_$_coldButton
    // Error parsing type: , name: $__lazy_storage_$_tipButton
    // Error parsing type: , name: $__lazy_storage_$_nameLabel
    // Error parsing type: , name: $__lazy_storage_$_locationLabel
    // Error parsing type: , name: $__lazy_storage_$_buttonStack
    // Error parsing type: , name: $__lazy_storage_$_mainStack
    // Error parsing type: , name: disposeBag
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

@interface _TtC5Jokes25JokeResultsViewController : UIViewController
{
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: socketCommand
    // Error parsing type: , name: socketCommands
    // Error parsing type: , name: winnerView
    // Error parsing type: , name: winnerNameLabel
    // Error parsing type: , name: winnerSocialLabel
    // Error parsing type: , name: hlsPlayer
    // Error parsing type: , name: $__lazy_storage_$_blurView
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Jokes15PassthroughView : UIView
{
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;

@end

@interface _TtC5JokesP33_524093F239E6E82967E6A9CB1E36744919TouchControlledView : UIView
{
    // Error parsing type: , name: touchArea
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Jokes18ChatViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate>
{
    // Error parsing type: , name: alphaAnimationKey
    // Error parsing type: , name: chatHeight
    // Error parsing type: , name: chatInputBecameFirstResponder
    // Error parsing type: , name: chatIsExpanded
    // Error parsing type: , name: keyboardIsExpanded
    // Error parsing type: , name: chatLayoutGuide
    // Error parsing type: , name: clearChatInputSubject
    // Error parsing type: , name: dismissChatSubject
    // Error parsing type: , name: data
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: keyboardConstraint
    // Error parsing type: , name: socketCommands
    // Error parsing type: , name: socketMessages
    // Error parsing type: , name: $__lazy_storage_$_blackOverlay
    // Error parsing type: , name: $__lazy_storage_$_expandToggleButton
    // Error parsing type: , name: $__lazy_storage_$_chatButton
    // Error parsing type: , name: $__lazy_storage_$_stackMask
    // Error parsing type: , name: $__lazy_storage_$_stackContainer
    // Error parsing type: , name: $__lazy_storage_$_tableView
    // Error parsing type: , name: $__lazy_storage_$_sendButton
    // Error parsing type: , name: messageTextFieldContainer
    // Error parsing type: , name: $__lazy_storage_$_unreadMessageButton
    // Error parsing type: , name: $__lazy_storage_$_messageTextField
    // Error parsing type: , name: textFieldDidReturnSubject
    // Error parsing type: , name: unreadContentHeightSubject
    // Error parsing type: , name: visibleIndexPaths
    // Error parsing type: , name: $__lazy_storage_$_chatHeightPublisher
    // Error parsing type: , name: messageFieldOffset
    // Error parsing type: , name: keyboardOffset
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)viewDidLayoutSubviews;
- (void)traitCollectionDidChange:(id)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Jokes17StatusMessageCell : UITableViewCell
{
    // Error parsing type: , name: messageLabel
    // Error parsing type: , name: statusIndicatorView
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

@interface _TtC5Jokes25JokeSessionViewController : UIViewController
{
    // Error parsing type: , name: feedbackGenerator
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: show
    // Error parsing type: , name: socketCommand
    // Error parsing type: , name: socketCommands
    // Error parsing type: , name: socketMessages
    // Error parsing type: , name: jokeSessionEnded
    // Error parsing type: , name: presentCoinsPurchaseModalPublisher
    // Error parsing type: , name: $__lazy_storage_$_meterView
    // Error parsing type: , name: $__lazy_storage_$_wheel
    // Error parsing type: , name: $__lazy_storage_$_countdownView
    // Error parsing type: , name: tippingUserView
    // Error parsing type: , name: $__lazy_storage_$_tipMeter
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end

@interface _TtC5Jokes30JokeRoundResultsViewController : UIViewController
{
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: socketCommand
    // Error parsing type: , name: socketCommands
    // Error parsing type: , name: $__lazy_storage_$_contestantsRow1StackView
    // Error parsing type: , name: $__lazy_storage_$_contestantsRow2StackView
    // Error parsing type: , name: $__lazy_storage_$_contestantContainer
    // Error parsing type: , name: $__lazy_storage_$_contestantsStackView
    // Error parsing type: , name: $__lazy_storage_$_blurView
    // Error parsing type: , name: $__lazy_storage_$_hostView
    // Error parsing type: , name: $__lazy_storage_$_titleLabel
    // Error parsing type: , name: hlsPlayer
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end

@interface _TtC5Jokes4Path : _TtCs12_SwiftObject
{
    // Error parsing type: , name: cmds
}

@end

@interface _TtC5Jokes6Socket : NSObject <NSObject>
{
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: messageQueue
    // Error parsing type: , name: socket
    // Error parsing type: , name: outgoingMessages
    // Error parsing type: , name: incomingMessagesSubject
}

- (void).cxx_destruct;
- (id)init;

@end

@interface _TtC5Jokes6Button : UIButton
{
    // Error parsing type: , name: isRounded
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Jokes18ContestantRankView : UIView
{
    // Error parsing type: , name: $__lazy_storage_$_imageView
    // Error parsing type: , name: outlineView
    // Error parsing type: , name: rankLabel
    // Error parsing type: , name: $__lazy_storage_$_rankView
    // Error parsing type: , name: style
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

@interface _TtC5Jokes11BundleClass : _TtCs12_SwiftObject
{
}

@end

__attribute__((visibility("hidden")))
@interface _TtC5Jokes15ChatMessageCell : UITableViewCell
{
    // Error parsing type: , name: avatarView
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: messageLabel
}

- (void).cxx_destruct;
- (void)prepareForReuse;
- (id)initWithCoder:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

@interface _TtC5Jokes29StarContestantsViewController : UIViewController
{
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: contestantTapped
    // Error parsing type: , name: socketCommand
    // Error parsing type: , name: socketCommands
    // Error parsing type: , name: sendSocketMessagePublisher
    // Error parsing type: , name: $__lazy_storage_$_contestantsRow1StackView
    // Error parsing type: , name: $__lazy_storage_$_contestantsRow2StackView
    // Error parsing type: , name: $__lazy_storage_$_contestantsStackView
    // Error parsing type: , name: $__lazy_storage_$_backgroundView
    // Error parsing type: , name: $__lazy_storage_$_hostView
    // Error parsing type: , name: $__lazy_storage_$_titleLabel
    // Error parsing type: , name: $__lazy_storage_$_timerLabel
    // Error parsing type: , name: hlsPlayer
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Jokes26JokeGiftDropViewController : UIViewController
{
    // Error parsing type: , name: didOpenGiftPublisher
    // Error parsing type: , name: giftDropAnimationFinishedPublisher
    // Error parsing type: , name: presentCoinsAnimationPublisher
    // Error parsing type: , name: $__lazy_storage_$_blurView
    // Error parsing type: , name: $__lazy_storage_$_hostView
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: hlsPlayer
    // Error parsing type: , name: show
    // Error parsing type: , name: gift
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)viewDidLoad;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Jokes18StarContestantView : UIView
{
    // Error parsing type: , name: $__lazy_storage_$_imageView
    // Error parsing type: , name: $__lazy_storage_$_nameLabel
    // Error parsing type: , name: $__lazy_storage_$_button
    // Error parsing type: , name: $__lazy_storage_$_ratingLabel
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: data
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Jokes12TipMeterView : UIView
{
    // Error parsing type: , name: $__lazy_storage_$_overlay
    // Error parsing type: , name: $__lazy_storage_$_underlay
    // Error parsing type: , name: constraint
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Jokes19JokeRoundResultView : UIView
{
    // Error parsing type: , name: $__lazy_storage_$_imageView
    // Error parsing type: , name: $__lazy_storage_$_nameLabel
    // Error parsing type: , name: $__lazy_storage_$_button
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: data
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Jokes9FlareView : MTKView
{
    // Error parsing type: , name: $__lazy_storage_$_commandQueue
    // Error parsing type: , name: $__lazy_storage_$_ciContext
    // Error parsing type: , name: mtlTexture
    // Error parsing type: , name: cornerAccent
    // Error parsing type: , name: accentOffset
    // Error parsing type: , name: tintRedA
    // Error parsing type: , name: tintRedB
    // Error parsing type: , name: tintBlueA
    // Error parsing type: , name: tintBlueB
    // Error parsing type: , name: offset
    // Error parsing type: , name: hotFactor
    // Error parsing type: , name: coldFactor
    // Error parsing type: , name: $__lazy_storage_$_hotAnimation
    // Error parsing type: , name: $__lazy_storage_$_coldAnimation
    // Error parsing type: , name: currentImage
    // Error parsing type: , name: animateInFactor
    // Error parsing type: , name: animateOutFactor
    // Error parsing type: , name: animateInAnimation
    // Error parsing type: , name: animateOutAnimation
    // Error parsing type: , name: context
    // Error parsing type: , name: mainImageRenderer
}

- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 device:(id)arg2;
@property(nonatomic) double coldFactor; // @synthesize coldFactor;
@property(nonatomic) double hotFactor; // @synthesize hotFactor;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Jokes23ExtraTimeMeterAnimation : UIView
{
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: animationDone
    // Error parsing type: , name: timer
    // Error parsing type: , name: soundTimer
    // Error parsing type: , name: $__lazy_storage_$_labelContainer
    // Error parsing type: , name: $__lazy_storage_$_starGlowContainer
    // Error parsing type: , name: $__lazy_storage_$_starContainer
    // Error parsing type: , name: $__lazy_storage_$_bigStarContainer
    // Error parsing type: , name: timeLabel
    // Error parsing type: , name: extraLabel
    // Error parsing type: , name: $__lazy_storage_$_timeContainer
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

@interface _TtCC5Jokes23ExtraTimeMeterAnimationP33_53028FDCC09D46A072D7054BB62460AB15CATransformView : UIView
{
}

+ (Class)layerClass;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Jokes15CircleHlsPlayer : UIView
{
    // Error parsing type: , name: $__lazy_storage_$_maskLayer
    // Error parsing type: , name: $__lazy_storage_$_playerView
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)init;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Jokes13CountdownView : _$s10HQSharedUI20CircularProgressViewCN
{
    // Error parsing type: , name: lastTotalTime
    // Error parsing type: , name: $__lazy_storage_$_label
    // Error parsing type: , name: timer
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Jokes21JokeMeterSectionsView : UIView
{
    // Error parsing type: , name: sections
    // Error parsing type: , name: $__lazy_storage_$_needle
    // Error parsing type: , name: highlightedSection
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

@interface _TtC5Jokes13ChatTextField : UITextField
{
}

- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (struct CGRect)editingRectForBounds:(struct CGRect)arg1;
- (struct CGRect)textRectForBounds:(struct CGRect)arg1;
- (void)layoutSubviews;
@property(nonatomic, readonly) struct CGSize intrinsicContentSize;

@end

__attribute__((visibility("hidden")))
@interface _TtC5Jokes10AvatarView : UIView
{
    // Error parsing type: , name: borderLayer
    // Error parsing type: , name: imageView
    // Error parsing type: , name: maskLayer
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;

@end

