//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark Named Structures

struct CGPoint {
    double _field1;
    double _field2;
};

struct CGRect {
    struct CGPoint _field1;
    struct CGSize _field2;
};

struct CGSize {
    double _field1;
    double _field2;
};

#pragma mark -

//
// File: Payload/HQ-iOS.app/Frameworks/HQSharedUI.framework/HQSharedUI
// UUID: 9610B32A-AB84-3260-B452-E41CA16B3522
//
//                           Arch: arm64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 0.0.0.0.0
//
// Objective-C Garbage Collection: Unsupported
//
//                       Run path: /usr/lib/swift
//                               = /usr/lib/swift
//                       Run path: @executable_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQSharedUI.framework/Frameworks
//                       Run path: @loader_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQSharedUI.framework/Frameworks
//                       Run path: @executable_path/../../Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQSharedUI.framework/../../Frameworks
//                       Run path: @executable_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQSharedUI.framework/Frameworks
//                       Run path: @loader_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQSharedUI.framework/Frameworks
//

@protocol CALayerDelegate <NSObject>

@optional
- (id <CAAction>)actionForLayer:(CALayer *)arg1 forKey:(NSString *)arg2;
- (void)layoutSublayersOfLayer:(CALayer *)arg1;
- (void)layerWillDraw:(CALayer *)arg1;
- (void)drawLayer:(CALayer *)arg1 inContext:(struct CGContext *)arg2;
- (void)displayLayer:(CALayer *)arg1;
@end

@protocol NSObject
@property(nonatomic, readonly) NSString *description;
- (struct _NSZone *)zone;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (_Bool)respondsToSelector:(SEL)arg1;
- (_Bool)conformsToProtocol:(Protocol *)arg1;
- (_Bool)isMemberOfClass:(Class)arg1;
- (_Bool)isKindOfClass:(Class)arg1;
- (_Bool)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (id)self;
- (Class)class;
@property(nonatomic, readonly) Class superclass;
@property(nonatomic, readonly) long long hash;
- (_Bool)isEqual:(id)arg1;

@optional
@property(nonatomic, readonly) NSString *debugDescription;
@end

@interface _TtC10HQSharedUI9AppSwitch : UIControl
{
    // Error parsing type: , name: images
    // Error parsing type: , name: isOn
    // Error parsing type: , name: backingButton
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)toggledWithTarget:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(nonatomic) _Bool enabled;
- (_Bool)isEnabled;

@end

@interface _TtC10HQSharedUI10PrizeLabel : UIView
{
    // Error parsing type: , name: backingCents
    // Error parsing type: , name: backingCurrency
    // Error parsing type: , name: backingFormatStyle
    // Error parsing type: , name: backingPoints
    // Error parsing type: , name: $__lazy_storage_$_centsLabel
    // Error parsing type: , name: font
    // Error parsing type: , name: $__lazy_storage_$_pointsLabel
    // Error parsing type: , name: $__lazy_storage_$_starImageView
    // Error parsing type: , name: starSize
    // Error parsing type: , name: textColor
}

- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

@interface _TtC10HQSharedUI18SharedGradientView : UIView
{
}

+ (Class)layerClass;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

@interface _TtC10HQSharedUIP33_6635969D1BF4898CE7C97ADBA3B920EE12NullDelegate : NSObject <CALayerDelegate>
{
}

- (id)init;
- (id)actionForLayer:(id)arg1 forKey:(id)arg2;

@end

@interface _TtC10HQSharedUI20CircularProgressView : UIView
{
    // Error parsing type: , name: nullDelegate
    // Error parsing type: , name: thickness
    // Error parsing type: , name: $__lazy_storage_$_backgroundRing
    // Error parsing type: , name: $__lazy_storage_$_ring
    // Error parsing type: , name: timeProvider
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;

@end

@interface _TtC10HQSharedUI14RoundImageView : UIView
{
    // Error parsing type: , name: $__lazy_storage_$_backingImageView
    // Error parsing type: , name: $__lazy_storage_$_circleLayer
    // Error parsing type: , name: contentSize
    // Error parsing type: , name: isRounded
    // Error parsing type: , name: isStroked
}

- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) long long contentMode;

@end

