//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark -

//
// File: Payload/HQ-iOS.app/Frameworks/Timing.framework/Timing
// UUID: A3F5AE59-AFD4-3DC3-BB89-50F1377D6CDF
//
//                           Arch: arm64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 0.0.0.0.0
//
// Objective-C Garbage Collection: Unsupported
//
//                       Run path: /usr/lib/swift
//                               = /usr/lib/swift
//                       Run path: @executable_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/Timing.framework/Frameworks
//                       Run path: @loader_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/Timing.framework/Frameworks
//                       Run path: @executable_path/../../Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/Timing.framework/../../Frameworks
//                       Run path: @executable_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/Timing.framework/Frameworks
//                       Run path: @loader_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/Timing.framework/Frameworks
//

@interface _TtC6Timing16TimerCancellable : _TtCs12_SwiftObject
{
    // Error parsing type: , name: handler
    // Error parsing type: , name: timer
}

@end

@interface _TtC6Timing13TimerProvider : _TtCs12_SwiftObject
{
}

@end

@interface _TtC6Timing17NewCountdownTimer : _TtCs12_SwiftObject
{
    // Error parsing type: , name: state
}

- (void)handleTick:(id)arg1;

@end

@interface _TtC6Timing14CountdownTimer : NSObject
{
    // Error parsing type: , name: onUpdate
    // Error parsing type: , name: lastTime
    // Error parsing type: , name: callbacks
    // Error parsing type: , name: duration
    // Error parsing type: , name: startTime
    // Error parsing type: , name: $__lazy_storage_$_displayLink
}

- (void).cxx_destruct;
- (id)init;
- (void)onDisplayLink;
- (void)dealloc;

@end

