//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct _NSRange {
    unsigned long long location;
    unsigned long long length;
};

#pragma mark -

//
// File: Payload/HQ-iOS.app/Frameworks/HQAnimation.framework/HQAnimation
// UUID: C8EAA2F7-25A6-3011-A417-7B456B69E8A6
//
//                           Arch: arm64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 0.0.0.0.0
//
// Objective-C Garbage Collection: Unsupported
//
//                       Run path: /usr/lib/swift
//                               = /usr/lib/swift
//                       Run path: @executable_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQAnimation.framework/Frameworks
//                       Run path: @loader_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQAnimation.framework/Frameworks
//                       Run path: @executable_path/../../Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQAnimation.framework/../../Frameworks
//                       Run path: @executable_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQAnimation.framework/Frameworks
//                       Run path: @loader_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQAnimation.framework/Frameworks
//

@protocol CAAnimationDelegate <NSObject>

@optional
- (void)animationDidStop:(CAAnimation *)arg1 finished:(_Bool)arg2;
- (void)animationDidStart:(CAAnimation *)arg1;
@end

@protocol NSObject
@property(nonatomic, readonly) NSString *description;
- (struct _NSZone *)zone;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (_Bool)respondsToSelector:(SEL)arg1;
- (_Bool)conformsToProtocol:(Protocol *)arg1;
- (_Bool)isMemberOfClass:(Class)arg1;
- (_Bool)isKindOfClass:(Class)arg1;
- (_Bool)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (id)self;
- (Class)class;
@property(nonatomic, readonly) Class superclass;
@property(nonatomic, readonly) long long hash;
- (_Bool)isEqual:(id)arg1;

@optional
@property(nonatomic, readonly) NSString *debugDescription;
@end

@interface HQAnimatedLabelAnimation : NSObject
{
    _Bool _interpolateValues;
    _Bool _randomOrder;
    _Bool _useSublayer;
    _Bool _removeAnimation;
    _Bool _adoptAnimationValueAtEnd;
    _Bool _additive;
    float _delay;
    float _duration;
    float _perUnitStartTimeOffset;
    float _durationRangeStart;
    float _durationRangeEnd;
    HQAnimatedLabelSpringSettings *_springSettings;
    unsigned long long _animationStartTimeOffsetAnchor;
    unsigned long long _easing;
    GKARC4RandomSource *_randomNumberGenerator;
    NSString *_keyPath;
    NSArray *_timingFunctions;
    NSArray *_values;
    CDUnknownBlockType _valueProvider;
    CDUnknownBlockType _onDone;
    NSArray *_relativeTimes;
    struct _NSRange _animatedRange;
}

- (void).cxx_destruct;
@property(nonatomic) float durationRangeEnd; // @synthesize durationRangeEnd=_durationRangeEnd;
@property(nonatomic) float durationRangeStart; // @synthesize durationRangeStart=_durationRangeStart;
@property(nonatomic) float perUnitStartTimeOffset; // @synthesize perUnitStartTimeOffset=_perUnitStartTimeOffset;
@property(nonatomic) float duration; // @synthesize duration=_duration;
@property(retain, nonatomic) NSArray *relativeTimes; // @synthesize relativeTimes=_relativeTimes;
@property(nonatomic) _Bool additive; // @synthesize additive=_additive;
@property(copy, nonatomic) CDUnknownBlockType onDone; // @synthesize onDone=_onDone;
@property(copy, nonatomic) CDUnknownBlockType valueProvider; // @synthesize valueProvider=_valueProvider;
@property(retain, nonatomic) NSArray *values; // @synthesize values=_values;
@property(retain, nonatomic) NSArray *timingFunctions; // @synthesize timingFunctions=_timingFunctions;
@property(nonatomic) float delay; // @synthesize delay=_delay;
@property(retain, nonatomic) NSString *keyPath; // @synthesize keyPath=_keyPath;
@property(nonatomic) struct _NSRange animatedRange; // @synthesize animatedRange=_animatedRange;
@property(nonatomic) _Bool adoptAnimationValueAtEnd; // @synthesize adoptAnimationValueAtEnd=_adoptAnimationValueAtEnd;
@property(nonatomic) _Bool removeAnimation; // @synthesize removeAnimation=_removeAnimation;
@property(nonatomic) _Bool useSublayer; // @synthesize useSublayer=_useSublayer;
@property(nonatomic) _Bool randomOrder; // @synthesize randomOrder=_randomOrder;
@property(nonatomic) _Bool interpolateValues; // @synthesize interpolateValues=_interpolateValues;
@property(retain, nonatomic) GKARC4RandomSource *randomNumberGenerator; // @synthesize randomNumberGenerator=_randomNumberGenerator;
@property(nonatomic) unsigned long long easing; // @synthesize easing=_easing;
@property(nonatomic) unsigned long long animationStartTimeOffsetAnchor; // @synthesize animationStartTimeOffsetAnchor=_animationStartTimeOffsetAnchor;
@property(retain, nonatomic) HQAnimatedLabelSpringSettings *springSettings; // @synthesize springSettings=_springSettings;
- (double)maximumTotalDurationForElementCount:(long long)arg1;
- (id)init;

@end

@interface HQAnimatedLabel : MKDynamicLabel
{
    HQAnimatedLabel *coloredLabel;
    NSMutableArray *activeAnimations;
}

- (void).cxx_destruct;
- (void)removeAnimations;
- (void)removeAnimationForKeypath:(id)arg1;
- (void)addReferenceWithObject:(id)arg1 animationKey:(id)arg2;
- (void)animateWithAnimation:(id)arg1;
- (void)setValues:(id)arg1 forSpringAnimation:(id)arg2;
- (void)animateWithDisplayLinkAndAnimation:(id)arg1;
- (void)setColorForLayer:(id)arg1 color:(id)arg2;
- (void)shuffleArray:(id)arg1 randomNumberGenerator:(id)arg2 seed:(id)arg3;
- (id)init;

@end

@interface HQAnimatedLabelAnimationReference : NSObject
{
    NSArray *_animatedObjects;
    NSString *_animationKey;
}

+ (id)referenceWithAnimatedObjects:(id)arg1 animationKey:(id)arg2;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *animationKey; // @synthesize animationKey=_animationKey;
@property(retain, nonatomic) NSArray *animatedObjects; // @synthesize animatedObjects=_animatedObjects;
- (void)removeAnimation;

@end

@interface HQAnimatedLabelSpringSettings : NSObject
{
    double _mass;
    double _stiffness;
    double _damping;
    double _initialVelocity;
}

@property(nonatomic) double initialVelocity; // @synthesize initialVelocity=_initialVelocity;
@property(nonatomic) double damping; // @synthesize damping=_damping;
@property(nonatomic) double stiffness; // @synthesize stiffness=_stiffness;
@property(nonatomic) double mass; // @synthesize mass=_mass;
@property(readonly, nonatomic) double duration;
- (id)init;

@end

@interface _TtC11HQAnimation17EnvironmentBridge : NSObject
{
}

+ (id)shared;
- (void).cxx_destruct;
- (id)init;
@property(nonatomic, readonly) double caTimeProvider;

@end

@interface _TtC11HQAnimation6Driver : NSObject
{
    // Error parsing type: , name: maxSteps
    // Error parsing type: , name: displayLink
    // Error parsing type: , name: animations
    // Error parsing type: , name: pausedAt
    // Error parsing type: , name: timestamp
    // Error parsing type: , name: currentSteps
    // Error parsing type: , name: previous
}

- (void).cxx_destruct;
- (id)init;
- (void)step:(id)arg1;
- (void)dealloc;

@end

@interface _TtC11HQAnimation17CAAnimationHandle : _TtCs12_SwiftObject
{
    // Error parsing type: , name: keyPath
    // Error parsing type: , name: additive
    // Error parsing type: , name: calculationMode
    // Error parsing type: , name: delay
    // Error parsing type: , name: delegate
    // Error parsing type: , name: duration
    // Error parsing type: , name: fillMode
    // Error parsing type: , name: fromValue
    // Error parsing type: , name: isRemovedOnCompletion
    // Error parsing type: , name: adoptModelValue
    // Error parsing type: , name: timingFunctions
    // Error parsing type: , name: toValue
    // Error parsing type: , name: values
    // Error parsing type: , name: valueProvider
}

@end

