//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark -

//
// File: Payload/HQ-iOS.app/Frameworks/HQCommon.framework/HQCommon
// UUID: 81FBDF56-92D1-3AF7-B1B1-EAB998DAB14E
//
//                           Arch: arm64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 0.0.0.0.0
//
// Objective-C Garbage Collection: Unsupported
//
//                       Run path: /usr/lib/swift
//                               = /usr/lib/swift
//                       Run path: @executable_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQCommon.framework/Frameworks
//                       Run path: @loader_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQCommon.framework/Frameworks
//                       Run path: @executable_path/../../Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQCommon.framework/../../Frameworks
//                       Run path: @executable_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQCommon.framework/Frameworks
//                       Run path: @loader_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQCommon.framework/Frameworks
//

@interface _TtC8HQCommonP33_06F8356185F20EBC72E0869948163F4C11BundleClass : _TtCs12_SwiftObject
{
}

@end

@interface _TtC8HQCommon19DispatchQueueUnique : NSObject
{
    // Error parsing type: , name: id
    // Error parsing type: , name: queue
}

- (void).cxx_destruct;
- (id)init;

@end

