//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct CGPoint {
    double _field1;
    double _field2;
};

struct CGRect {
    struct CGPoint _field1;
    struct CGSize _field2;
};

struct CGSize {
    double _field1;
    double _field2;
};

#pragma mark -

//
// File: Payload/HQ-iOS.app/Frameworks/HQGiftDrop.framework/HQGiftDrop
// UUID: 12068D99-0B2B-38C6-A4C6-2651EE7115C9
//
//                           Arch: arm64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 0.0.0.0.0
//
// Objective-C Garbage Collection: Unsupported
//
//                       Run path: /usr/lib/swift
//                               = /usr/lib/swift
//                       Run path: @executable_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQGiftDrop.framework/Frameworks
//                       Run path: @loader_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQGiftDrop.framework/Frameworks
//                       Run path: @executable_path/../../Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQGiftDrop.framework/../../Frameworks
//                       Run path: @executable_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQGiftDrop.framework/Frameworks
//                       Run path: @loader_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQGiftDrop.framework/Frameworks
//

@protocol NSObject
@property(nonatomic, readonly) NSString *description;
- (struct _NSZone *)zone;
- (unsigned long long)retainCount;
- (id)autorelease;
- (oneway void)release;
- (id)retain;
- (_Bool)respondsToSelector:(SEL)arg1;
- (_Bool)conformsToProtocol:(Protocol *)arg1;
- (_Bool)isMemberOfClass:(Class)arg1;
- (_Bool)isKindOfClass:(Class)arg1;
- (_Bool)isProxy;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2 withObject:(id)arg3;
- (id)performSelector:(SEL)arg1 withObject:(id)arg2;
- (id)performSelector:(SEL)arg1;
- (id)self;
- (Class)class;
@property(nonatomic, readonly) Class superclass;
@property(nonatomic, readonly) long long hash;
- (_Bool)isEqual:(id)arg1;

@optional
@property(nonatomic, readonly) NSString *debugDescription;
@end

@protocol SLLayerProtocol <NSObject>
- (SLProperty *)propertyWithPath:(NSString *)arg1;
- (SLProperty *)propertyWithName:(NSString *)arg1;
- (NSArray *)markersWithComment:(NSString *)arg1;
- (void)evaluateExpressions;
@property(nonatomic, readonly) NSArray *markers;
@property(nonatomic, readonly) NSArray *properties;
@property(nonatomic, readonly) NSArray *expressionControls;
@end

@interface GiftDropTapController : UIView
{
    MKiAnimation *tapAnimation;
    MKiAnimation *zRotationAnimation;
    MKiAnimation *xRotationAnimation;
    UIButton *button;
    SLProperty *zProperty;
    SLProperty *xProperty;
    MKDisplayLinkAnimation *forceOpenAnimation;
    _Bool _enabled;
    SLSquallAnimation *_giftDropAnimation;
    CDUnknownBlockType _onDidTap;
    CDUnknownBlockType _onTapTargetReached;
    double _tapProgress;
    double _zRotation;
    double _xRotation;
}

- (void).cxx_destruct;
@property(nonatomic) double xRotation; // @synthesize xRotation=_xRotation;
@property(nonatomic) double zRotation; // @synthesize zRotation=_zRotation;
@property(nonatomic) double tapProgress; // @synthesize tapProgress=_tapProgress;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
@property(copy, nonatomic) CDUnknownBlockType onTapTargetReached; // @synthesize onTapTargetReached=_onTapTargetReached;
@property(copy, nonatomic) CDUnknownBlockType onDidTap; // @synthesize onDidTap=_onDidTap;
@property(retain, nonatomic) SLSquallAnimation *giftDropAnimation; // @synthesize giftDropAnimation=_giftDropAnimation;
- (void)forceOpen;
- (void)onTap;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

@interface _TtC10HQGiftDrop20GiftAnimationBuilder : _TtCs12_SwiftObject
{
}

@end

@interface _TtC10HQGiftDrop4Gift : _TtCs12_SwiftObject
{
    // Error parsing type: , name: amount
    // Error parsing type: , name: dropId
    // Error parsing type: , name: giftDropClosed
    // Error parsing type: , name: giftDropOpened
    // Error parsing type: , name: openDelayMs
    // Error parsing type: , name: timeLeftMs
    // Error parsing type: , name: type
}

@end

@interface _TtC10HQGiftDropP33_3C6AE9C659A933CF3CD0F92F20CB87E311BundleClass : _TtCs12_SwiftObject
{
}

@end

@interface _TtC10HQGiftDrop12GiftDropView : UIView
{
    // Error parsing type: , name: buttonHeight
    // Error parsing type: , name: state
    // Error parsing type: , name: giftAnimateInTime
    // Error parsing type: , name: animatingInCutOffTime
    // Error parsing type: , name: aniChest
    // Error parsing type: , name: timer
    // Error parsing type: , name: forceOpenTimer
    // Error parsing type: , name: chestAnimationScalar
    // Error parsing type: , name: gift
    // Error parsing type: , name: giftImage
    // Error parsing type: , name: giftAnimation
    // Error parsing type: , name: animationSize
    // Error parsing type: , name: onLoaded
    // Error parsing type: , name: onDone
    // Error parsing type: , name: shouldPlay
    // Error parsing type: , name: disposeBag
    // Error parsing type: , name: giftOpenedPublisher
    // Error parsing type: , name: $__lazy_storage_$_giftDropTapController
    // Error parsing type: , name: show
    // Error parsing type: , name: $__lazy_storage_$_button
    // Error parsing type: , name: $__lazy_storage_$_label
}

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)onTimer;
- (void)pressedButton;
- (void)layoutSubviews;
- (id)initWithCoder:(id)arg1;

@end

@interface NSObject (Animation)
- (void)removeiAnimation:(id)arg1;
- (void)removeAlliAnimations;
- (void)addiAnimation:(id)arg1;
@end

