//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Oct 25 2017 03:49:04).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark -

//
// File: Payload/HQ-iOS.app/Frameworks/HQAPI.framework/HQAPI
// UUID: EAFC8137-3DCA-35C4-A499-D183270D359A
//
//                           Arch: arm64
//                Current version: 1.0.0
//          Compatibility version: 1.0.0
//                 Source version: 0.0.0.0.0
//
// Objective-C Garbage Collection: Unsupported
//
//                       Run path: /usr/lib/swift
//                               = /usr/lib/swift
//                       Run path: @executable_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQAPI.framework/Frameworks
//                       Run path: @loader_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQAPI.framework/Frameworks
//                       Run path: @executable_path/../../Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQAPI.framework/../../Frameworks
//                       Run path: @executable_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQAPI.framework/Frameworks
//                       Run path: @loader_path/Frameworks
//                               = Payload/HQ-iOS.app/Frameworks/HQAPI.framework/Frameworks
//

@interface _TtC5HQAPI6Router : _TtCs12_SwiftObject
{
    // Error parsing type: , name: _retrying
    // Error parsing type: , name: additionalHeaders
    // Error parsing type: , name: authenticate
    // Error parsing type: , name: baseUri
    // Error parsing type: , name: defaultHeaders
    // Error parsing type: , name: isAuthenticated
    // Error parsing type: , name: onResponse
    // Error parsing type: , name: retries
    // Error parsing type: , name: retryQueue
}

@end

@interface _TtC5HQAPI20NearbyUsersProviding : _TtCs12_SwiftObject
{
    // Error parsing type: , name: updates
    // Error parsing type: , name: start
    // Error parsing type: , name: stop
}

@end

